export const SORT_OPTIONS = {
  ALPHABETICAL: 'alphabetical',
  CATEGORICAL: 'categorical',
} as const;

export type SortOption = (typeof SORT_OPTIONS)[keyof typeof SORT_OPTIONS];

export const COMPONENT_CATEGORIES: Record<string, string[]> = {
  Actions: ['ActionGroup', 'Button', 'ButtonLink', 'CloseButton', 'ControlButton', 'Link', 'SplitButton'],
  Content: [
    'Accordion',
    'Avatar',
    'Card',
    'EmptyState',
    'Item',
    'Pill',
    'PricingPlan',
    'Tag',
    'Timeline',
    'UNSTABLE_SplitTag',
    'UNSTABLE_Table',
    'UNSTABLE_Tile',
  ],
  Feedback: ['Alert', 'ProgressBar', 'Skeleton', 'Spinner', 'Toast'],
  'Form Primitives': [
    'CharacterCounter',
    'HelperText',
    'InputAddon',
    'InputContainer',
    'InputDetails',
    'Label',
    'TextFieldBase',
    'ValidationText',
  ],
  Forms: [
    'Checkbox',
    'FieldGroup',
    'File',
    'FileUpload',
    'Radio',
    'SegmentedControl',
    'Select',
    'Slider',
    'TextArea',
    'TextField',
    'Toggle',
    'UNSTABLE_Combobox',
    'UNSTABLE_Picker',
  ],
  Layout: ['Box', 'Container', 'Divider', 'Flex', 'Grid', 'Matrix', 'ScrollView', 'Section', 'Stack'],
  'Media and Icons': ['Icon', 'IconBox', 'PartnerLogo', 'ProductLogo'],
  Navigation: ['Breadcrumbs', 'Footer', 'Header', 'Navigation', 'Pagination', 'SkipLink', 'Tabs'],
  Overlays: ['ContextualHelp', 'Dialog', 'Drawer', 'Dropdown', 'Modal', 'Tooltip'],
  Typography: ['ActionText', 'CaptionText', 'Heading', 'Text', 'UNSTABLE_DisplayHeading'],
  Utilities: ['Collapse', 'Hidden', 'NoSsr', 'Truncate', 'VisuallyHidden'],
};
