/* This file was generated by Supernova, don't change manually */
export const accent01BackgroundBasic = '#b60000';
export const accent01BackgroundSubtle = '#fce5e5';
export const accent01BorderBasic = '#b60000';
export const accent01BorderSubtle = '#fce5e5';
export const accent01ContentBasic = '#b60000';
export const accent01ContentSubtle = '#fce5e5';
export const accent01StateActive = '#facccc';
export const accent01StateDefault = '#fef2f2';
export const accent01StateHover = '#fce5e5';

export const accent02BackgroundBasic = '#ffbe00';
export const accent02BackgroundSubtle = '#fff7ee';
export const accent02BorderBasic = '#ffcb3b';
export const accent02BorderSubtle = '#fff7ee';
export const accent02ContentBasic = '#ff6a00';
export const accent02ContentSubtle = '#fff8e5';
export const accent02StateActive = '#cc9800';
export const accent02StateDefault = '#ffbe00';
export const accent02StateHover = '#e5ab00';

export const accent03BackgroundBasic = '#404040';
export const accent03BackgroundSubtle = '#f2f2f2';
export const accent03BorderBasic = '#404040';
export const accent03BorderSubtle = '#f2f2f2';
export const accent03ContentBasic = '#404040';
export const accent03ContentSubtle = '#f2f2f2';
export const accent03StateActive = '#d9d9d9';
export const accent03StateDefault = '#f2f2f2';
export const accent03StateHover = '#e5e5e5';

export const accent04BackgroundBasic = '#006e36';
export const accent04BackgroundSubtle = '#f2f9f5';
export const accent04BorderBasic = '#006e36';
export const accent04BorderSubtle = '#f2f9f5';
export const accent04ContentBasic = '#006e36';
export const accent04ContentSubtle = '#f2f9f5';
export const accent04StateActive = '#cce8d9';
export const accent04StateDefault = '#f2f9f5';
export const accent04StateHover = '#e5f3ec';

export const accent05BackgroundBasic = '#e61f60';
export const accent05BackgroundSubtle = '#f5f6fa';
export const accent05BorderBasic = '#e61f60';
export const accent05BorderSubtle = '#f28faf';
export const accent05ContentBasic = '#e61f60';
export const accent05ContentSubtle = '#fff';
export const accent05StateActive = '#cf1652';
export const accent05StateDefault = '#e61f60';
export const accent05StateHover = '#d91958';

export const accent06BackgroundBasic = '#ffcb3b';
export const accent06BackgroundSubtle = '#fffaeb';
export const accent06BorderBasic = '#ffd562';
export const accent06BorderSubtle = '#ffefc4';
export const accent06ContentBasic = '#cca22f';
export const accent06ContentSubtle = '#ffcb3b';
export const accent06StateActive = '#ffda75';
export const accent06StateDefault = '#ffcb3b';
export const accent06StateHover = '#ffd562';

export const backgroundBackdrop = '#1a1b1b40';

export const backgroundInteractiveStateActive = '#e5e5e5';
export const backgroundInteractiveStateDefault = '#fff0';
export const backgroundInteractiveStateHover = '#f2f2f2';

export const backgroundPrimary = '#fff';
export const backgroundSecondary = '#f9f9f9';
export const backgroundTertiary = '#fbf7f4';

export const borderBasic = '#e5e5e5';
export const borderFocus = '#0074e8';

export const borderInteractiveStateActive = '#a5a5a5';
export const borderInteractiveStateDefault = '#d9d9d9';
export const borderInteractiveStateHover = '#b2b2b2';
export const borderInteractiveStateSelected = '#202020';

export const componentButtonPlainBorder = '#fff0';
export const componentButtonPlainContent = '#0074e8';
export const componentButtonPlainStateActive = '#f2f2f2';
export const componentButtonPlainStateDefault = '#fff0';
export const componentButtonPlainStateHover = '#f9f9f9';

export const componentButtonPrimaryBorder = '#a68426';
export const componentButtonPrimaryContent = '#000';
export const componentButtonPrimaryStateActive = '#ffda75';
export const componentButtonPrimaryStateDefault = '#ffcb3b';
export const componentButtonPrimaryStateHover = '#ffd562';

export const componentButtonSecondaryBorder = '#000';
export const componentButtonSecondaryContent = '#202020';
export const componentButtonSecondaryStateActive = '#fffaeb';
export const componentButtonSecondaryStateDefault = '#fff';
export const componentButtonSecondaryStateHover = '#fffcf5';

export const componentButtonTertiaryBorder = '#7f7f7f';
export const componentButtonTertiaryContent = '#202020';
export const componentButtonTertiaryStateActive = '#f9f9f9';
export const componentButtonTertiaryStateDefault = '#e5e5e5';
export const componentButtonTertiaryStateHover = '#f2f2f2';

export const componentHeaderBackground = '#1a1b1b00';
export const componentHeaderBorder = '#e5e5e5';

export const componentNavigationItemBackgroundStateActive = '#f2f2f2';
export const componentNavigationItemBackgroundStateDefault = '#fff0';
export const componentNavigationItemBackgroundStateHover = '#f9f9f9';
export const componentNavigationItemBackgroundStateSelected = '#fff5d8';
export const componentNavigationItemStateActive = '#202020';
export const componentNavigationItemStateDefault = '#535353';
export const componentNavigationItemStateHover = '#404040';
export const componentNavigationItemStateSelected = '#202020';
export const componentNavigationItemStripeStateSelected = '#ffcb3b';
export const componentNavigationItemStripeStateUnselected = '#fff0';

export const componentPaginationSelectedBorder = '#e6b735';
export const componentPaginationSelectedContent = '#000';
export const componentPaginationSelectedStateActive = '#ffda75';
export const componentPaginationSelectedStateDefault = '#ffcb3b';
export const componentPaginationSelectedStateHover = '#ffd562';
export const componentPaginationUnselectedBorder = '#bfbfbf';
export const componentPaginationUnselectedContent = '#000';
export const componentPaginationUnselectedStateActive = '#f2f2f2';
export const componentPaginationUnselectedStateDefault = '#fff';
export const componentPaginationUnselectedStateHover = '#f9f9f9';

export const componentPricingPlanHighlightedBackground = '#fff7ee';
export const componentPricingPlanHighlightedBorder = '#ffcb3b';
export const componentPricingPlanHighlightedContent = '#ff6a00';

export const componentTagSelectedBackground = '#ffbe00';
export const componentTagSelectedBorder = '#fbbb00';
export const componentTagSelectedContent = '#202020';

export const componentToggleSelectedBorder = '#006e36';
export const componentToggleSelectedContent = '#fff';
export const componentToggleSelectedStateActive = '#008a43';
export const componentToggleSelectedStateDefault = '#006e36';
export const componentToggleSelectedStateHover = '#007c3c';
export const componentToggleUnselectedBorder = '#a5a5a5';
export const componentToggleUnselectedContent = '#404040';
export const componentToggleUnselectedStateActive = '#f2f2f2';
export const componentToggleUnselectedStateDefault = '#fff';
export const componentToggleUnselectedStateHover = '#f9f9f9';

export const disabledBackground = '#f9f9f9';
export const disabledBorder = '#e5e5e5';
export const disabledContent = '#727272';
export const disabledForeground = '#d9d9d9';

export const emotionDangerBackgroundBasic = '#b60000';
export const emotionDangerBackgroundSubtle = '#fef2f2';
export const emotionDangerBorderBasic = '#b60000';
export const emotionDangerBorderSubtle = '#f18080';
export const emotionDangerContentBasic = '#940000';
export const emotionDangerContentSubtle = '#fff';
export const emotionDangerStateActive = '#e40000';
export const emotionDangerStateDefault = '#b60000';
export const emotionDangerStateHover = '#cd0000';

export const emotionInformativeBackgroundBasic = '#005dba';
export const emotionInformativeBackgroundSubtle = '#f2f8fe';
export const emotionInformativeBorderBasic = '#005dba';
export const emotionInformativeBorderSubtle = '#7fb9f3';
export const emotionInformativeContentBasic = '#004c97';
export const emotionInformativeContentSubtle = '#fff';
export const emotionInformativeStateActive = '#0074e8';
export const emotionInformativeStateDefault = '#005dba';
export const emotionInformativeStateHover = '#0069d1';

export const emotionSuccessBackgroundBasic = '#006e36';
export const emotionSuccessBackgroundSubtle = '#f2f9f5';
export const emotionSuccessBorderBasic = '#006e36';
export const emotionSuccessBorderSubtle = '#7fc4a1';
export const emotionSuccessContentBasic = '#005a2c';
export const emotionSuccessContentSubtle = '#fff';
export const emotionSuccessStateActive = '#008a43';
export const emotionSuccessStateDefault = '#006e36';
export const emotionSuccessStateHover = '#007c3c';

export const emotionWarningBackgroundBasic = '#c26400';
export const emotionWarningBackgroundSubtle = '#fef8f2';
export const emotionWarningBorderBasic = '#c26400';
export const emotionWarningBorderSubtle = '#f9be80';
export const emotionWarningContentBasic = '#9d5100';
export const emotionWarningContentSubtle = '#fff';
export const emotionWarningStateActive = '#f27d00';
export const emotionWarningStateDefault = '#c26400';
export const emotionWarningStateHover = '#da7100';

export const focusFocusRingColor01 = '#0074e840';

export const formFieldDanger = '#b60000';

export const formFieldFillBackgroundStateActive = '#fff';
export const formFieldFillBackgroundStateDefault = '#fff';
export const formFieldFillBackgroundStateHover = '#f9f9f9';
export const formFieldFillBorderStateActive = '#7f7f7f';
export const formFieldFillBorderStateDefault = '#a5a5a5';
export const formFieldFillBorderStateHover = '#999';
export const formFieldFillBorderStateSelected = '#ffcb3b';
export const formFieldFillContent = '#202020';
export const formFieldFillPlaceholder = '#535353';

export const formFieldHelperText = '#727272';
export const formFieldLabel = '#202020';

export const formFieldOutlineBackgroundStateActive = '#fff';
export const formFieldOutlineBackgroundStateDefault = '#1a1b1b00';
export const formFieldOutlineBackgroundStateHover = '#fff';
export const formFieldOutlineBorderStateActive = '#fff';
export const formFieldOutlineBorderStateDefault = '#a5a5a5';
export const formFieldOutlineBorderStateHover = '#fff';
export const formFieldOutlineBorderStateSelected = '#fff';
export const formFieldOutlineContent = '#202020';
export const formFieldOutlinePlaceholder = '#535353';

export const formFieldSuccess = '#006e36';
export const formFieldWarning = '#c26400';

export const gradientBasicOverlayColor01 = '#fff';
export const gradientBasicOverlayColor02 = '#fff0';

export const gradientPrimaryColor01 = '#c30c13';
export const gradientPrimaryColor02 = '#e4192a';
export const gradientPrimaryColor03 = '#e4192a';

export const gradientSecondaryColor01 = '#c30c13';
export const gradientSecondaryColor02 = '#e4192a';
export const gradientSecondaryColor03 = '#e4192a';

export const gradientSkeletonColor01 = '#e5e5e5';
export const gradientSkeletonColor02 = '#fff';
export const gradientSkeletonColor03 = '#e5e5e5';

export const linkPrimaryStateActive = '#004c97';
export const linkPrimaryStateDefault = '#0069d1';
export const linkPrimaryStateHover = '#005dba';

export const linkSecondaryStateActive = '#202020';
export const linkSecondaryStateDefault = '#535353';
export const linkSecondaryStateHover = '#404040';

export const linkStateVisited = '#3c2480';

export const linkTertiaryStateActive = '#727272';
export const linkTertiaryStateDefault = '#a5a5a5';
export const linkTertiaryStateHover = '#7f7f7f';

export const neutralBackgroundBasic = '#202020';
export const neutralBackgroundSubtle = '#f2f2f2';
export const neutralBorderBasic = '#202020';
export const neutralBorderSubtle = '#bfbfbf';
export const neutralContentBasic = '#202020';
export const neutralContentSubtle = '#fff';
export const neutralStateActive = '#535353';
export const neutralStateDefault = '#202020';
export const neutralStateHover = '#404040';

export const selectedBackgroundBasic = '#ffcb3b';
export const selectedBackgroundSubtle = '#ffefc4';
export const selectedBorderBasic = '#cca22f';
export const selectedBorderSubtle = '#ffda75';
export const selectedContentBasic = '#202020';
export const selectedContentSubtle = '#202020';
export const selectedStateActive = '#ffda75';
export const selectedStateDefault = '#ffcb3b';
export const selectedStateHover = '#ffd562';

export const shadowShadow100Color01 = '#00000026';

export const shadowShadow200Color01 = '#0003';

export const shadowShadow300Color01 = '#00000040';

export const shadowShadow400Color01 = '#00000040';

export const textPrimary = '#202020';
export const textSecondary = '#535353';
export const textTertiary = '#7f7f7f';
