name: 'setup node'
description: 'Setup Node'
inputs:
  node-version:
    description: 'Node.js version to use. If not provided, version is read from .nvmrc file'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Set up Node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && '.nvmrc' || '' }}
        registry-url: 'https://registry.npmjs.org'
