name: 'setup node'
description: 'Setup Node'
inputs:
  node-version:
    description: 'Node.js version to use. If not provided, version is read from .nvmrc file'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Set up Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && '.nvmrc' || '' }}
        registry-url: 'https://registry.npmjs.org'
