/* This file was generated by Supernova, don't change manually */
export const gridSpacingMobile = '1rem';
export const gridSpacingDesktop = '2rem';
export const gridSpacingTablet = '2rem';

export const containerXsmallMaxWidth = '41rem';

export const containerSmallMaxWidth = '44rem';

export const containerMediumMaxWidth = '54rem';

export const containerLargeMaxWidth = '67rem';

export const containerXlargeMaxWidth = '80rem';

export const containerXxlargeMaxWidth = '100rem';

export const gridColumns = '12';

export const cssVariablePrefix = 'spirit-';

export const containerPaddingDesktop = '2rem';
export const containerPaddingMobile = '1rem';
export const containerPaddingTablet = '2rem';

export const containerMaxWidth = '80rem';

export const grids = {
  spacing: {
    mobile: gridSpacingMobile,
    desktop: gridSpacingDesktop,
    tablet: gridSpacingTablet,
  },
  columns: gridColumns,
};

export const containers = {
  xsmall: {
    maxWidth: containerXsmallMaxWidth,
  },
  small: {
    maxWidth: containerSmallMaxWidth,
  },
  medium: {
    maxWidth: containerMediumMaxWidth,
  },
  large: {
    maxWidth: containerLargeMaxWidth,
  },
  xlarge: {
    maxWidth: containerXlargeMaxWidth,
  },
  xxlarge: {
    maxWidth: containerXxlargeMaxWidth,
  },
  padding: {
    desktop: containerPaddingDesktop,
    mobile: containerPaddingMobile,
    tablet: containerPaddingTablet,
  },
  maxWidth: containerMaxWidth,
};
