/* This file was generated by Supernova, don't change manually */
export const space0 = 0;
export const space100 = '0.0625rem';
export const space1000 = '2rem';
export const space1100 = '2.5rem';
export const space1200 = '3rem';
export const space1300 = '3.5rem';
export const space1400 = '4rem';
export const space1500 = '4.5rem';
export const space1600 = '5rem';
export const space1700 = '6rem';
export const space200 = '0.125rem';
export const space300 = '0.25rem';
export const space400 = '0.375rem';
export const space500 = '0.5rem';
export const space600 = '0.75rem';
export const space700 = '1rem';
export const space800 = '1.25rem';
export const space900 = '1.5rem';

export const spaces = {
  0: space0,
  100: space100,
  200: space200,
  300: space300,
  400: space400,
  500: space500,
  600: space600,
  700: space700,
  800: space800,
  900: space900,
  1000: space1000,
  1100: space1100,
  1200: space1200,
  1300: space1300,
  1400: space1400,
  1500: space1500,
  1600: space1600,
  1700: space1700,
};
