/* This file was generated by Supernova, don't change manually */
export const actionLarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3333,
  },
};

export const actionMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.25,
  },
};

export const actionSmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1429,
  },
};

export const bodyLargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4444,
  },
};

export const bodyLargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4444,
  },
};

export const italicUnderline = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'italic',
    fontWeight: 400,
  },
};

export const bodyLargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4444,
  },
};

export const bodyLargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4444,
  },
};

export const bodyMediumBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyMediumRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyMediumSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodySmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4286,
  },
};

export const bodySmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const bodySmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const bodySmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4286,
  },
};

export const bodyXlargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.6,
  },
};

export const bodyXlargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.6,
  },
};

export const bodyXlargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.6,
  },
};

export const bodyXlargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.6,
  },
};

export const bodyXsmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.3333,
  },
};

export const bodyXsmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.3333,
  },
};

export const bodyXsmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.3333,
  },
};

export const bodyXsmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3333,
  },
};

export const caption = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
  },
};

export const codeLargeBold = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5556,
  },
};

export const codeLargeRegular = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5556,
  },
};

export const codeMediumBold = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const codeMediumRegular = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const codeSmallBold = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4286,
  },
};

export const codeSmallRegular = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const displayLarge = {
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '0px',
    fontStyle: 'normal',
    fontWeight: 600,
  },
};

export const displayMedium = {
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '0px',
    fontStyle: 'normal',
    fontWeight: 600,
  },
};

export const displaySmall = {
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '0px',
    fontStyle: 'normal',
    fontWeight: 600,
  },
};

export const eyebrow = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const headingLargeBold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.375rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2105,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.375rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2105,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.75rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.0714,
  },
};

export const headingLargeItalic = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.375rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2105,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.375rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2105,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.75rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.0714,
  },
};

export const headingLargeRegular = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.375rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2105,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.375rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2105,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.75rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.0714,
  },
};

export const headingLargeSemibold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.375rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2105,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.375rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2105,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.0714,
  },
};

export const headingMediumBold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.3125,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.3125,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1667,
  },
};

export const headingMediumItalic = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.3125,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.3125,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
};

export const headingMediumRegular = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.3125,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.3125,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
};

export const headingMediumSemibold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3125,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3125,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1667,
  },
};

export const bold = {
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
  },
};

export const italic = {
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
  },
};

export const regular = {
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
  },
};

export const semibold = {
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
  },
};

export const headingSmallBold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.625rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.3846,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.625rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.3846,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
};

export const headingSmallItalic = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.625rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.3846,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.625rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.3846,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingSmallRegular = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.625rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.3846,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.625rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.3846,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingSmallSemibold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.625rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3846,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.625rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3846,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
};

export const headingXlargeBold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.75rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1818,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.75rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1818,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1765,
  },
};

export const headingXlargeItalic = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.75rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1818,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.75rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1818,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.125rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1765,
  },
};

export const headingXlargeRegular = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.75rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1818,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.75rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1818,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1765,
  },
};

export const headingXlargeSemibold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1818,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1818,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '2.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1765,
  },
};

export const headingXsmallBold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2222,
  },
};

export const headingXsmallItalic = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2222,
  },
};

export const headingXsmallRegular = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2222,
  },
};

export const headingXsmallSemibold = {
  desktop: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  mobile: {
    fontFamily: "'sofia-pro', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2222,
  },
};

export const inputLarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5556,
  },
};

export const inputMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const inputSmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const labelLarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3333,
  },
};

export const labelMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.25,
  },
};

export const labelSmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1429,
  },
};

export const labelXlarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
};

export const labelXsmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3333,
  },
};

export const styles = {
  actionLarge,
  actionMedium,
  actionSmall,
  bodyLargeBold,
  bodyLargeItalic,
  italicUnderline,
  bodyLargeRegular,
  bodyLargeSemibold,
  bodyMediumBold,
  bodyMediumItalic,
  bodyMediumRegular,
  bodyMediumSemibold,
  bodySmallBold,
  bodySmallItalic,
  bodySmallRegular,
  bodySmallSemibold,
  bodyXlargeBold,
  bodyXlargeItalic,
  bodyXlargeRegular,
  bodyXlargeSemibold,
  bodyXsmallBold,
  bodyXsmallItalic,
  bodyXsmallRegular,
  bodyXsmallSemibold,
  caption,
  codeLargeBold,
  codeLargeRegular,
  codeMediumBold,
  codeMediumRegular,
  codeSmallBold,
  codeSmallRegular,
  displayLarge,
  displayMedium,
  displaySmall,
  eyebrow,
  headingLargeBold,
  headingLargeItalic,
  headingLargeRegular,
  headingLargeSemibold,
  headingMediumBold,
  headingMediumItalic,
  headingMediumRegular,
  headingMediumSemibold,
  bold,
  italic,
  regular,
  semibold,
  headingSmallBold,
  headingSmallItalic,
  headingSmallRegular,
  headingSmallSemibold,
  headingXlargeBold,
  headingXlargeItalic,
  headingXlargeRegular,
  headingXlargeSemibold,
  headingXsmallBold,
  headingXsmallItalic,
  headingXsmallRegular,
  headingXsmallSemibold,
  inputLarge,
  inputMedium,
  inputSmall,
  labelLarge,
  labelMedium,
  labelSmall,
  labelXlarge,
  labelXsmall,
};
