---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: designSystems-spiritAnalytics
  description: Analytic tools for Spirit Design System
  annotations:
    github.com/project-slug: alma-oss/spirit-design-system
    backstage.io/source-location: url:https://github.com/alma-oss/spirit-design-system/tree/main/packages/analytics
    ac/communication-channel: https://almamedia.slack.com/archives/C068XPSDWQN
  links:
    - url: https://spiritdesignsystem.com
      title: Spirit Design System website
    - url: https://backstage.almacareer.tech/catalog/default/component/designSystems-spiritWebReact/docs
      title: Main Developer Documentation
  tags:
    - designsystem
    - spirit
    - analytics
spec:
  type: library
  lifecycle: production
  owner: user:default/tomas.litera
  system: designSystems-spiritDesignSystem
  dependsOn:
    - technology:default/typescript
    - technology:default/eslint
    - technology:default/jest
    - technology:default/yarn
    - technology:default/github
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: designSystems-spiritCodemods
  description: Codemods scripts for Spirit Design System packages
  annotations:
    github.com/project-slug: alma-oss/spirit-design-system
    backstage.io/source-location: url:https://github.com/alma-oss/spirit-design-system/tree/main/packages/codemods
    ac/communication-channel: https://almamedia.slack.com/archives/C068XPSDWQN
  links:
    - url: https://spiritdesignsystem.com
      title: Spirit Design System website
    - url: https://backstage.almacareer.tech/catalog/default/component/designSystems-spiritWebReact/docs
      title: Main Developer Documentation
  tags:
    - designsystem
    - spirit
    - codemods
spec:
  type: library
  lifecycle: production
  owner: user:default/tomas.litera
  system: designSystems-spiritDesignSystem
  dependsOn:
    - technology:default/typescript
    - technology:default/eslint
    - technology:default/jest
    - technology:default/yarn
    - technology:default/github
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: designSystems-spiritDesignTokens
  description: Design tokens for Spirit Design System
  annotations:
    github.com/project-slug: alma-oss/spirit-design-system
    backstage.io/source-location: url:https://github.com/alma-oss/spirit-design-system/tree/main/packages/design-tokens
    ac/communication-channel: https://almamedia.slack.com/archives/C068XPSDWQN
  links:
    - url: https://spiritdesignsystem.com
      title: Spirit Design System website
    - url: https://backstage.almacareer.tech/catalog/default/component/designSystems-spiritWebReact/docs
      title: Main Developer Documentation
  tags:
    - designsystem
    - spirit
    - designtokens
spec:
  type: library
  lifecycle: production
  owner: user:default/tomas.litera
  system: designSystems-spiritDesignSystem
  dependsOn:
    - technology:default/typescript
    - technology:default/eslint
    - technology:default/yarn
    - technology:default/github
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: designSystems-spiritIcons
  description: Icons for Spirit Design System
  annotations:
    github.com/project-slug: alma-oss/spirit-design-system
    backstage.io/source-location: url:https://github.com/alma-oss/spirit-design-system/tree/main/packages/icons
    ac/communication-channel: https://almamedia.slack.com/archives/C068XPSDWQN
  links:
    - url: https://spiritdesignsystem.com
      title: Spirit Design System website
    - url: https://backstage.almacareer.tech/catalog/default/component/designSystems-spiritWebReact/docs
      title: Main Developer Documentation
  tags:
    - designsystem
    - spirit
    - icons
spec:
  type: library
  lifecycle: production
  owner: user:default/tomas.litera
  system: designSystems-spiritDesignSystem
  dependsOn:
    - technology:default/typescript
    - technology:default/reactjs
    - technology:default/jest
    - technology:default/yarn
    - technology:default/github
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: designSystems-spiritWeb
  description: CSS and vanilla JS implementation of Spirit Design System
  annotations:
    github.com/project-slug: alma-oss/spirit-design-system
    backstage.io/source-location: url:https://github.com/alma-oss/spirit-design-system/tree/main/packages/web
    ac/communication-channel: https://almamedia.slack.com/archives/C068XPSDWQN
  links:
    - url: https://spiritdesignsystem.com
      title: Spirit Design System website
    - url: https://backstage.almacareer.tech/catalog/default/component/designSystems-spiritWeb/docs
      title: Main Developer Documentation
  tags:
    - designsystem
    - spirit
    - web
spec:
  type: library
  lifecycle: production
  owner: user:default/tomas.litera
  system: designSystems-spiritDesignSystem
  dependsOn:
    - technology:default/typescript
    - technology:default/javascript
    - technology:default/eslint
    - technology:default/jest
    - technology:default/yarn
    - technology:default/github
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: designSystems-spiritWebReact
  description: React implementation of Spirit Design System components
  annotations:
    github.com/project-slug: alma-oss/spirit-design-system
    backstage.io/source-location: url:https://github.com/alma-oss/spirit-design-system/tree/main/packages/web-react
    backstage.io/techdocs-ref: dir:.
    ac/communication-channel: https://almamedia.slack.com/archives/C068XPSDWQN
  tags:
    - designsystem
    - spirit
    - webreact
  links:
    - url: https://spiritdesignsystem.com
      title: Spirit Design System website
    - url: https://almamedia.slack.com/archives/C068XPSDWQN
      title: Support spirit-design-system Slack channel
spec:
  type: library
  lifecycle: production
  owner: user:default/tomas.litera
  system: designSystems-spiritDesignSystem
  dependsOn:
    - technology:default/typescript
    - technology:default/reactjs
    - technology:default/javascript
    - technology:default/eslint
    - technology:default/jest
    - technology:default/figma
    - technology:default/yarn
    - technology:default/github
