name: 'setup and install'
description: 'Setup Node and Install Dependencies'
inputs:
  node-version:
    description: 'Node.js version to use. If not provided, version is read from .nvmrc file'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore Cache
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: ./.yarn/cache
        key: ${{ runner.os }}-Yarn-main
        restore-keys: |
          ${{ runner.os }}-Yarn-main-

    - name: Install dependencies
      uses: ./.github/actions/deps-install
