/* This file was generated by Supernova, don't change manually */
export const containerXsmallMaxWidth = '480px';

export const containerSmallMaxWidth = '640px';

export const containerMediumMaxWidth = '768px';

export const containerLargeMaxWidth = '1024px';

export const containerXlargeMaxWidth = '1280px';

export const gridSpacingMobile = '16px';
export const gridSpacingDesktop = '32px';
export const gridSpacingTablet = '32px';

export const gridColumns = '12';

export const cssVariablePrefix = 'spirit-';

export const containerPaddingMobile = '16px';
export const containerPaddingTablet = '32px';
export const containerPaddingDesktop = '32px';

export const containerMaxWidth = '1280px';

export const containers = {
  xsmall: {
    maxWidth: containerXsmallMaxWidth,
  },
  small: {
    maxWidth: containerSmallMaxWidth,
  },
  medium: {
    maxWidth: containerMediumMaxWidth,
  },
  large: {
    maxWidth: containerLargeMaxWidth,
  },
  xlarge: {
    maxWidth: containerXlargeMaxWidth,
  },
  padding: {
    mobile: containerPaddingMobile,
    tablet: containerPaddingTablet,
    desktop: containerPaddingDesktop,
  },
  maxWidth: containerMaxWidth,
};

export const grids = {
  spacing: {
    mobile: gridSpacingMobile,
    desktop: gridSpacingDesktop,
    tablet: gridSpacingTablet,
  },
  columns: gridColumns,
};
