/* This file was generated by Supernova, don't change manually */
export const focusRing = '0 0 0 0.125rem var(--spirit-color-focus-focus-ring-color-01, #d2c2ffb2)';

export const shadow100 = '0 0.125rem 0.5rem 0 var(--spirit-color-shadow-shadow-100-color-01, #0000001a)';
export const shadow200 = '0 0.25rem 0.75rem 0 var(--spirit-color-shadow-shadow-200-color-01, #0003)';
export const shadow300 = '0 0.5rem 1.5rem 0 var(--spirit-color-shadow-shadow-300-color-01, #00000040)';
export const shadow400 = '0 0.75rem 2rem 0 var(--spirit-color-shadow-shadow-400-color-01, #00000040)';

export const focus = {
  focusRing,
};

export const shadows = {
  100: shadow100,
  200: shadow200,
  300: shadow300,
  400: shadow400,
};
