/* This file was generated by Supernova, don't change manually */
export const focusRing = 'var(--spirit-focus-ring-offset-x, 0) var(--spirit-focus-ring-offset-y, 0) var(--spirit-focus-ring-blur-radius, 0) var(--spirit-focus-ring-spread-radius, 0.125rem) var(--spirit-color-focus-focus-ring-color-01, #d2c2ffb2)';

export const shadow100 = 'var(--spirit-shadow-100-offset-x, 0) var(--spirit-shadow-100-offset-y, 0.125rem) var(--spirit-shadow-100-blur-radius, 0.5rem) var(--spirit-shadow-100-spread-radius, 0) var(--spirit-color-shadow-shadow-100-color-01, #0000001a)';
export const shadow200 = 'var(--spirit-shadow-200-offset-x, 0) var(--spirit-shadow-200-offset-y, 0.25rem) var(--spirit-shadow-200-blur-radius, 0.75rem) var(--spirit-shadow-200-spread-radius, 0) var(--spirit-color-shadow-shadow-200-color-01, #0003)';
export const shadow300 = 'var(--spirit-shadow-300-offset-x, 0) var(--spirit-shadow-300-offset-y, 0.5rem) var(--spirit-shadow-300-blur-radius, 1.5rem) var(--spirit-shadow-300-spread-radius, 0) var(--spirit-color-shadow-shadow-300-color-01, #00000040)';
export const shadow400 = 'var(--spirit-shadow-400-offset-x, 0) var(--spirit-shadow-400-offset-y, 0.75rem) var(--spirit-shadow-400-blur-radius, 2rem) var(--spirit-shadow-400-spread-radius, 0) var(--spirit-color-shadow-shadow-400-color-01, #00000040)';

export const focus = {
  focusRing,
};

export const shadows = {
  100: shadow100,
  200: shadow200,
  300: shadow300,
  400: shadow400,
};
