/* This file was generated by Supernova, don't change manually */
export const actionLarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.33,
  },
};

export const actionMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.25,
  },
};

export const actionSmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.14,
  },
};

export const bodyLargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.56,
  },
};

export const bodyLargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.56,
  },
};

export const bodyLargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.56,
  },
};

export const bodyLargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.56,
  },
};

export const bodyMediumBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.50,
  },
};

export const bodyMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.50,
  },
};

export const bodyMediumRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.50,
  },
};

export const bodyMediumSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.50,
  },
};

export const bodySmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.43,
  },
};

export const bodySmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.43,
  },
};

export const bodySmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.43,
  },
};

export const bodySmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.43,
  },
};

export const bodyXlargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.60,
  },
};

export const bodyXlargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.60,
  },
};

export const bodyXlargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.60,
  },
};

export const bodyXlargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.60,
  },
};

export const bodyXsmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.67,
  },
};

export const bodyXsmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.67,
  },
};

export const bodyXsmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.67,
  },
};

export const bodyXsmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.67,
  },
};

export const caption = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.25,
  },
};

export const codeLargeBold = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.56,
  },
};

export const codeLargeRegular = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.56,
  },
};

export const codeMediumBold = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.50,
  },
};

export const codeMediumRegular = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.50,
  },
};

export const codeSmallBold = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.43,
  },
};

export const codeSmallRegular = {
  mobile: {
    fontFamily: "'Roboto Mono', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.43,
  },
};

export const displayLarge = {
  mobile: {
    fontFamily: "'General Sans', sans-serif",
    fontSize: '4.75rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.13,
  },
};

export const displayMedium = {
  mobile: {
    fontFamily: "'General Sans', sans-serif",
    fontSize: '3.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.21,
  },
};

export const displaySmall = {
  mobile: {
    fontFamily: "'General Sans', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.17,
  },
};

export const eyebrow = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.25,
  },
};

export const headingLargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.19,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
};

export const headingLargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.19,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
};

export const headingLargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.19,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
};

export const headingLargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.19,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
};

export const headingMediumBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.19,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.19,
  },
};

export const headingMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.19,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.19,
  },
};

export const headingMediumRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.19,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.19,
  },
};

export const headingMediumSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.19,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.19,
  },
};

export const headingSmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.17,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.17,
  },
};

export const headingSmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.17,
  },
};

export const headingSmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.17,
  },
};

export const headingSmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.17,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.17,
  },
};

export const headingXlargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.21,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.21,
  },
};

export const headingXlargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.21,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.21,
  },
};

export const headingXlargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.21,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.21,
  },
};

export const headingXlargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.21,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.21,
  },
};

export const headingXsmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.22,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
};

export const headingXsmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.22,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
};

export const headingXsmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.22,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
};

export const headingXsmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.22,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
};

export const inputLarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.56,
  },
};

export const inputMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.50,
  },
};

export const inputSmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.43,
  },
};

export const labelLarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.33,
  },
};

export const labelMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.25,
  },
};

export const labelSmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.14,
  },
};

export const labelXlarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.40,
  },
};

export const labelXsmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.33,
  },
};

export const styles = {
  bodyLargeBold,
  bodyLargeItalic,
  bodyLargeRegular,
  bodyLargeSemibold,
  bodyMediumBold,
  bodyMediumItalic,
  bodyMediumRegular,
  bodyMediumSemibold,
  bodySmallBold,
  bodySmallItalic,
  bodySmallRegular,
  bodySmallSemibold,
  bodyXlargeBold,
  bodyXlargeItalic,
  bodyXlargeRegular,
  bodyXlargeSemibold,
  bodyXsmallBold,
  bodyXsmallItalic,
  bodyXsmallRegular,
  bodyXsmallSemibold,
  headingLargeBold,
  headingLargeItalic,
  headingLargeRegular,
  headingLargeSemibold,
  headingMediumBold,
  headingMediumItalic,
  headingMediumRegular,
  headingMediumSemibold,
  headingSmallBold,
  headingSmallItalic,
  headingSmallRegular,
  headingSmallSemibold,
  headingXlargeBold,
  headingXlargeItalic,
  headingXlargeRegular,
  headingXlargeSemibold,
  headingXsmallBold,
  headingXsmallItalic,
  headingXsmallRegular,
  headingXsmallSemibold,
};
