/* This file was generated by Supernova, don't change manually */
export const actionLarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3333,
  },
};

export const actionMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.25,
  },
};

export const actionSmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1429,
  },
};

export const bodyLargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5556,
  },
};

export const bodyLargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5556,
  },
};

export const bodyLargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5556,
  },
};

export const bodyLargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5556,
  },
};

export const bodyMediumBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const bodyMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyMediumRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const bodyMediumSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.5,
  },
};

export const bodySmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4286,
  },
};

export const bodySmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const bodySmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const bodySmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4286,
  },
};

export const bodyXlargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.6,
  },
};

export const bodyXlargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.6,
  },
};

export const bodyXlargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.6,
  },
};

export const bodyXlargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.6,
  },
};

export const bodyXsmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.6667,
  },
};

export const bodyXsmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.6667,
  },
};

export const bodyXsmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.6667,
  },
};

export const bodyXsmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.6667,
  },
};

export const caption = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const codeLargeBold = {
  mobile: {
    fontFamily: "'Roboto Mono', monospace",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5556,
  },
};

export const codeLargeRegular = {
  mobile: {
    fontFamily: "'Roboto Mono', monospace",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5556,
  },
};

export const codeMediumBold = {
  mobile: {
    fontFamily: "'Roboto Mono', monospace",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.5,
  },
};

export const codeMediumRegular = {
  mobile: {
    fontFamily: "'Roboto Mono', monospace",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const codeSmallBold = {
  mobile: {
    fontFamily: "'Roboto Mono', monospace",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.4286,
  },
};

export const codeSmallRegular = {
  mobile: {
    fontFamily: "'Roboto Mono', monospace",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const displayLarge = {
  mobile: {
    fontFamily: "'General Sans', sans-serif",
    fontSize: '4.75rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1316,
  },
};

export const displayMedium = {
  mobile: {
    fontFamily: "'General Sans', sans-serif",
    fontSize: '3.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2143,
  },
};

export const displaySmall = {
  mobile: {
    fontFamily: "'General Sans', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1667,
  },
};

export const eyebrow = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4286,
  },
};

export const headingLargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1875,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
};

export const headingLargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1875,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingLargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1875,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingLargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1875,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
};

export const headingMediumBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1667,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1875,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1875,
  },
};

export const headingMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1875,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1875,
  },
};

export const headingMediumRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1875,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1875,
  },
};

export const headingMediumSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1667,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1875,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1875,
  },
};

export const headingSmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1667,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1667,
  },
};

export const headingSmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
};

export const headingSmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
};

export const headingSmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1667,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1667,
  },
};

export const headingXlargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.1667,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2083,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2083,
  },
};

export const headingXlargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2083,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2083,
  },
};

export const headingXlargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.1667,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2083,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2083,
  },
};

export const headingXlargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1667,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2083,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2083,
  },
};

export const headingXsmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2222,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.2,
  },
};

export const headingXsmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2222,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingXsmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2222,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.2,
  },
};

export const headingXsmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2222,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.2,
  },
};

export const inputLarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5556,
  },
};

export const inputMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.5,
  },
};

export const inputSmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.4286,
  },
};

export const labelLarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3333,
  },
};

export const labelMedium = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.25,
  },
};

export const labelSmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.1429,
  },
};

export const labelXlarge = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.4,
  },
};

export const labelXsmall = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.3333,
  },
};

export const styles = {
  actionLarge,
  actionMedium,
  actionSmall,
  bodyLargeBold,
  bodyLargeItalic,
  bodyLargeRegular,
  bodyLargeSemibold,
  bodyMediumBold,
  bodyMediumItalic,
  bodyMediumRegular,
  bodyMediumSemibold,
  bodySmallBold,
  bodySmallItalic,
  bodySmallRegular,
  bodySmallSemibold,
  bodyXlargeBold,
  bodyXlargeItalic,
  bodyXlargeRegular,
  bodyXlargeSemibold,
  bodyXsmallBold,
  bodyXsmallItalic,
  bodyXsmallRegular,
  bodyXsmallSemibold,
  caption,
  codeLargeBold,
  codeLargeRegular,
  codeMediumBold,
  codeMediumRegular,
  codeSmallBold,
  codeSmallRegular,
  displayLarge,
  displayMedium,
  displaySmall,
  eyebrow,
  headingLargeBold,
  headingLargeItalic,
  headingLargeRegular,
  headingLargeSemibold,
  headingMediumBold,
  headingMediumItalic,
  headingMediumRegular,
  headingMediumSemibold,
  headingSmallBold,
  headingSmallItalic,
  headingSmallRegular,
  headingSmallSemibold,
  headingXlargeBold,
  headingXlargeItalic,
  headingXlargeRegular,
  headingXlargeSemibold,
  headingXsmallBold,
  headingXsmallItalic,
  headingXsmallRegular,
  headingXsmallSemibold,
  inputLarge,
  inputMedium,
  inputSmall,
  labelLarge,
  labelMedium,
  labelSmall,
  labelXlarge,
  labelXsmall,
};
