/* This file was generated by Supernova, don't change manually */
export const bodyLargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.33,
  },
};

export const bodyLargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.33,
  },
};

export const bodyLargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.33,
  },
};

export const bodyLargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.33,
  },
};

export const bodyMediumBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.38,
  },
};

export const bodyMediumItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.38,
  },
};

export const bodyMediumRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.38,
  },
};

export const bodyMediumSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.38,
  },
};

export const bodySmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.43,
  },
};

export const bodySmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.43,
  },
};

export const bodySmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.43,
  },
};

export const bodySmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.43,
  },
};

export const bodyXlargeBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.40,
  },
};

export const bodyXlargeItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.40,
  },
};

export const bodyXlargeRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.40,
  },
};

export const bodyXlargeSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.40,
  },
};

export const bodyXsmallBold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.33,
  },
};

export const bodyXsmallItalic = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.33,
  },
};

export const bodyXsmallRegular = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.33,
  },
};

export const bodyXsmallSemibold = {
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.75rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.33,
  },
};

export const headingLargeBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.19,
  },
};

export const headingLargeItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.19,
  },
};

export const headingLargeRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.19,
  },
};

export const headingLargeSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.19,
  },
};

export const headingMediumBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.19,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.19,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.17,
  },
};

export const headingMediumItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.19,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.19,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.17,
  },
};

export const headingMediumRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.19,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.19,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.17,
  },
};

export const headingMediumSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.19,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.19,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.17,
  },
};

export const headingSmallBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.17,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
};

export const headingSmallItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
};

export const headingSmallRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.17,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
};

export const headingSmallSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.17,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.5rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.17,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
};

export const headingXlargeBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.21,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.21,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.17,
  },
};

export const headingXlargeItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.21,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.21,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.17,
  },
};

export const headingXlargeRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.21,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.21,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.17,
  },
};

export const headingXlargeSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.21,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.21,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '2.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.17,
  },
};

export const headingXsmallBold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.20,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 1.22,
  },
};

export const headingXsmallItalic = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'italic',
    fontWeight: 400,
    lineHeight: 1.22,
  },
};

export const headingXsmallRegular = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.20,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 1.22,
  },
};

export const headingXsmallSemibold = {
  desktop: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
  tablet: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.20,
  },
  mobile: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '1.125rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 1.22,
  },
};

export const styles = {
  bodyLargeBold,
  bodyLargeItalic,
  bodyLargeRegular,
  bodyLargeSemibold,
  bodyMediumBold,
  bodyMediumItalic,
  bodyMediumRegular,
  bodyMediumSemibold,
  bodySmallBold,
  bodySmallItalic,
  bodySmallRegular,
  bodySmallSemibold,
  bodyXlargeBold,
  bodyXlargeItalic,
  bodyXlargeRegular,
  bodyXlargeSemibold,
  bodyXsmallBold,
  bodyXsmallItalic,
  bodyXsmallRegular,
  bodyXsmallSemibold,
  headingLargeBold,
  headingLargeItalic,
  headingLargeRegular,
  headingLargeSemibold,
  headingMediumBold,
  headingMediumItalic,
  headingMediumRegular,
  headingMediumSemibold,
  headingSmallBold,
  headingSmallItalic,
  headingSmallRegular,
  headingSmallSemibold,
  headingXlargeBold,
  headingXlargeItalic,
  headingXlargeRegular,
  headingXlargeSemibold,
  headingXsmallBold,
  headingXsmallItalic,
  headingXsmallRegular,
  headingXsmallSemibold,
};
