/* This file was generated by Supernova, don't change manually */
export const radius0 = 0;
export const radius100 = '0.125rem';
export const radius200 = '0.25rem';
export const radius300 = '0.5rem';
export const radius400 = '0.75rem';
export const radius500 = '1rem';
export const radiusFull = '624.9375rem';

export const radii = {
  0: radius0,
  100: radius100,
  200: radius200,
  300: radius300,
  400: radius400,
  500: radius500,
  full: radiusFull,
};
