/* This file was generated by Supernova, don't change manually */
export const formFieldLargeRadiusDesktop = '0.5rem';
export const formFieldLargeRadiusMobile = '0.5rem';
export const formFieldLargeRadiusTablet = '0.5rem';

export const formFieldMediumRadiusDesktop = '0.5rem';
export const formFieldMediumRadiusMobile = '0.5rem';
export const formFieldMediumRadiusTablet = '0.5rem';

export const formFieldSmallRadiusDesktop = '0.5rem';
export const formFieldSmallRadiusMobile = '0.5rem';
export const formFieldSmallRadiusTablet = '0.5rem';

export const fontSizeBaseDesktop = '16px';
export const fontSizeBaseMobile = '16px';
export const fontSizeBaseTablet = '16px';

export const buttonLargeRadiusDesktop = '624.9375rem';
export const buttonLargeRadiusMobile = '624.9375rem';
export const buttonLargeRadiusTablet = '624.9375rem';

export const buttonMediumRadiusDesktop = '624.9375rem';
export const buttonMediumRadiusMobile = '624.9375rem';
export const buttonMediumRadiusTablet = '624.9375rem';

export const buttonSmallRadiusDesktop = '624.9375rem';
export const buttonSmallRadiusMobile = '624.9375rem';
export const buttonSmallRadiusTablet = '624.9375rem';

export const breakpointMobile = 0;
export const breakpointTablet = '48rem';
export const breakpointDesktop = '80rem';

export const typographyBodyXsmallFontSizeDesktop = '0.75rem';
export const typographyBodyXsmallFontSizeMobile = '0.75rem';
export const typographyBodyXsmallFontSizeTablet = '0.75rem';

export const typographyBodySmallFontSizeDesktop = '0.875rem';
export const typographyBodySmallFontSizeMobile = '0.875rem';
export const typographyBodySmallFontSizeTablet = '0.875rem';

export const typographyBodyMediumFontSizeDesktop = '1rem';
export const typographyBodyMediumFontSizeMobile = '1rem';
export const typographyBodyMediumFontSizeTablet = '1rem';

export const typographyBodyLargeFontSizeDesktop = '1.125rem';
export const typographyBodyLargeFontSizeMobile = '1.125rem';
export const typographyBodyLargeFontSizeTablet = '1.125rem';

export const typographyHeadingXsmallFontSizeMobile = '1.125rem';

export const typographyBodyXlargeFontSizeDesktop = '1.25rem';
export const typographyBodyXlargeFontSizeMobile = '1.25rem';
export const typographyBodyXlargeFontSizeTablet = '1.25rem';

export const typographyHeadingSmallFontSizeMobile = '1.25rem';

export const typographyHeadingXsmallFontSizeDesktop = '1.25rem';
export const typographyHeadingXsmallFontSizeTablet = '1.25rem';

export const typographyHeadingMediumFontSizeMobile = '1.5rem';

export const typographyHeadingSmallFontSizeDesktop = '1.5rem';
export const typographyHeadingSmallFontSizeTablet = '1.5rem';

export const typographyHeadingLargeFontSizeMobile = '2rem';

export const typographyHeadingMediumFontSizeDesktop = '2rem';
export const typographyHeadingMediumFontSizeTablet = '2rem';

export const typographyHeadingXlargeFontSizeMobile = '2.25rem';

export const typographyHeadingLargeFontSizeDesktop = '2.5rem';
export const typographyHeadingLargeFontSizeTablet = '2.5rem';

export const typographyHeadingXlargeFontSizeDesktop = '3rem';
export const typographyHeadingXlargeFontSizeTablet = '3rem';

export const typographyBodyXsmallLineHeightDesktop = '1rem';
export const typographyBodyXsmallLineHeightMobile = '1rem';
export const typographyBodyXsmallLineHeightTablet = '1rem';

export const typographyBodySmallLineHeightDesktop = '1.25rem';
export const typographyBodySmallLineHeightMobile = '1.25rem';
export const typographyBodySmallLineHeightTablet = '1.25rem';

export const typographyBodyMediumLineHeightDesktop = '1.375rem';
export const typographyBodyMediumLineHeightMobile = '1.375rem';
export const typographyBodyMediumLineHeightTablet = '1.375rem';

export const typographyHeadingXsmallLineHeightMobile = '1.375rem';

export const typographyBodyLargeLineHeightDesktop = '1.5rem';
export const typographyBodyLargeLineHeightMobile = '1.5rem';
export const typographyBodyLargeLineHeightTablet = '1.5rem';

export const typographyHeadingSmallLineHeightMobile = '1.5rem';

export const typographyHeadingXsmallLineHeightDesktop = '1.5rem';
export const typographyHeadingXsmallLineHeightTablet = '1.5rem';

export const typographyBodyXlargeLineHeightDesktop = '1.75rem';
export const typographyBodyXlargeLineHeightMobile = '1.75rem';
export const typographyBodyXlargeLineHeightTablet = '1.75rem';

export const typographyHeadingMediumLineHeightMobile = '1.75rem';

export const typographyHeadingSmallLineHeightDesktop = '1.75rem';
export const typographyHeadingSmallLineHeightTablet = '1.75rem';

export const typographyHeadingLargeLineHeightMobile = '2.375rem';

export const typographyHeadingMediumLineHeightDesktop = '2.375rem';
export const typographyHeadingMediumLineHeightTablet = '2.375rem';

export const typographyHeadingXlargeLineHeightMobile = '2.625rem';

export const typographyHeadingLargeLineHeightDesktop = '3rem';
export const typographyHeadingLargeLineHeightTablet = '3rem';

export const typographyHeadingXlargeLineHeightDesktop = '3.625rem';
export const typographyHeadingXlargeLineHeightTablet = '3.625rem';

export const typographyBodyLargeLetterSpacingDesktop = 0;
export const typographyBodyLargeLetterSpacingMobile = 0;
export const typographyBodyLargeLetterSpacingTablet = 0;

export const typographyBodyMediumLetterSpacingDesktop = 0;
export const typographyBodyMediumLetterSpacingMobile = 0;
export const typographyBodyMediumLetterSpacingTablet = 0;

export const typographyBodySmallLetterSpacingDesktop = 0;
export const typographyBodySmallLetterSpacingMobile = 0;
export const typographyBodySmallLetterSpacingTablet = 0;

export const typographyBodyXlargeLetterSpacingDesktop = 0;
export const typographyBodyXlargeLetterSpacingMobile = 0;
export const typographyBodyXlargeLetterSpacingTablet = 0;

export const typographyBodyXsmallLetterSpacingDesktop = 0;
export const typographyBodyXsmallLetterSpacingMobile = 0;
export const typographyBodyXsmallLetterSpacingTablet = 0;

export const typographyHeadingLargeLetterSpacingDesktop = 0;
export const typographyHeadingLargeLetterSpacingMobile = 0;
export const typographyHeadingLargeLetterSpacingTablet = 0;

export const typographyHeadingMediumLetterSpacingDesktop = 0;
export const typographyHeadingMediumLetterSpacingMobile = 0;
export const typographyHeadingMediumLetterSpacingTablet = 0;

export const typographyHeadingSmallLetterSpacingDesktop = 0;
export const typographyHeadingSmallLetterSpacingMobile = 0;
export const typographyHeadingSmallLetterSpacingTablet = 0;

export const typographyHeadingXlargeLetterSpacingDesktop = 0;
export const typographyHeadingXlargeLetterSpacingMobile = 0;
export const typographyHeadingXlargeLetterSpacingTablet = 0;

export const typographyHeadingXsmallLetterSpacingDesktop = 0;
export const typographyHeadingXsmallLetterSpacingMobile = 0;
export const typographyHeadingXsmallLetterSpacingTablet = 0;

export const formFields = {
  large: {
    radius: {
      desktop: formFieldLargeRadiusDesktop,
      mobile: formFieldLargeRadiusMobile,
      tablet: formFieldLargeRadiusTablet,
    },
  },
  medium: {
    radius: {
      desktop: formFieldMediumRadiusDesktop,
      mobile: formFieldMediumRadiusMobile,
      tablet: formFieldMediumRadiusTablet,
    },
  },
  small: {
    radius: {
      desktop: formFieldSmallRadiusDesktop,
      mobile: formFieldSmallRadiusMobile,
      tablet: formFieldSmallRadiusTablet,
    },
  },
};

export const fontSizeBases = {
  desktop: fontSizeBaseDesktop,
  mobile: fontSizeBaseMobile,
  tablet: fontSizeBaseTablet,
};

export const buttons = {
  large: {
    radius: {
      desktop: buttonLargeRadiusDesktop,
      mobile: buttonLargeRadiusMobile,
      tablet: buttonLargeRadiusTablet,
    },
  },
  medium: {
    radius: {
      desktop: buttonMediumRadiusDesktop,
      mobile: buttonMediumRadiusMobile,
      tablet: buttonMediumRadiusTablet,
    },
  },
  small: {
    radius: {
      desktop: buttonSmallRadiusDesktop,
      mobile: buttonSmallRadiusMobile,
      tablet: buttonSmallRadiusTablet,
    },
  },
};

export const breakpoints = {
  mobile: breakpointMobile,
  tablet: breakpointTablet,
  desktop: breakpointDesktop,
};

export const typographys = {
  body: {
    xsmall: {
      fontSize: {
        desktop: typographyBodyXsmallFontSizeDesktop,
        mobile: typographyBodyXsmallFontSizeMobile,
        tablet: typographyBodyXsmallFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodyXsmallLineHeightDesktop,
        mobile: typographyBodyXsmallLineHeightMobile,
        tablet: typographyBodyXsmallLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodyXsmallLetterSpacingDesktop,
        mobile: typographyBodyXsmallLetterSpacingMobile,
        tablet: typographyBodyXsmallLetterSpacingTablet,
      },
    },
    small: {
      fontSize: {
        desktop: typographyBodySmallFontSizeDesktop,
        mobile: typographyBodySmallFontSizeMobile,
        tablet: typographyBodySmallFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodySmallLineHeightDesktop,
        mobile: typographyBodySmallLineHeightMobile,
        tablet: typographyBodySmallLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodySmallLetterSpacingDesktop,
        mobile: typographyBodySmallLetterSpacingMobile,
        tablet: typographyBodySmallLetterSpacingTablet,
      },
    },
    medium: {
      fontSize: {
        desktop: typographyBodyMediumFontSizeDesktop,
        mobile: typographyBodyMediumFontSizeMobile,
        tablet: typographyBodyMediumFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodyMediumLineHeightDesktop,
        mobile: typographyBodyMediumLineHeightMobile,
        tablet: typographyBodyMediumLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodyMediumLetterSpacingDesktop,
        mobile: typographyBodyMediumLetterSpacingMobile,
        tablet: typographyBodyMediumLetterSpacingTablet,
      },
    },
    large: {
      fontSize: {
        desktop: typographyBodyLargeFontSizeDesktop,
        mobile: typographyBodyLargeFontSizeMobile,
        tablet: typographyBodyLargeFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodyLargeLineHeightDesktop,
        mobile: typographyBodyLargeLineHeightMobile,
        tablet: typographyBodyLargeLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodyLargeLetterSpacingDesktop,
        mobile: typographyBodyLargeLetterSpacingMobile,
        tablet: typographyBodyLargeLetterSpacingTablet,
      },
    },
    xlarge: {
      fontSize: {
        desktop: typographyBodyXlargeFontSizeDesktop,
        mobile: typographyBodyXlargeFontSizeMobile,
        tablet: typographyBodyXlargeFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodyXlargeLineHeightDesktop,
        mobile: typographyBodyXlargeLineHeightMobile,
        tablet: typographyBodyXlargeLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodyXlargeLetterSpacingDesktop,
        mobile: typographyBodyXlargeLetterSpacingMobile,
        tablet: typographyBodyXlargeLetterSpacingTablet,
      },
    },
  },
  heading: {
    xsmall: {
      fontSize: {
        mobile: typographyHeadingXsmallFontSizeMobile,
        desktop: typographyHeadingXsmallFontSizeDesktop,
        tablet: typographyHeadingXsmallFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingXsmallLineHeightMobile,
        desktop: typographyHeadingXsmallLineHeightDesktop,
        tablet: typographyHeadingXsmallLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingXsmallLetterSpacingDesktop,
        mobile: typographyHeadingXsmallLetterSpacingMobile,
        tablet: typographyHeadingXsmallLetterSpacingTablet,
      },
    },
    small: {
      fontSize: {
        mobile: typographyHeadingSmallFontSizeMobile,
        desktop: typographyHeadingSmallFontSizeDesktop,
        tablet: typographyHeadingSmallFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingSmallLineHeightMobile,
        desktop: typographyHeadingSmallLineHeightDesktop,
        tablet: typographyHeadingSmallLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingSmallLetterSpacingDesktop,
        mobile: typographyHeadingSmallLetterSpacingMobile,
        tablet: typographyHeadingSmallLetterSpacingTablet,
      },
    },
    medium: {
      fontSize: {
        mobile: typographyHeadingMediumFontSizeMobile,
        desktop: typographyHeadingMediumFontSizeDesktop,
        tablet: typographyHeadingMediumFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingMediumLineHeightMobile,
        desktop: typographyHeadingMediumLineHeightDesktop,
        tablet: typographyHeadingMediumLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingMediumLetterSpacingDesktop,
        mobile: typographyHeadingMediumLetterSpacingMobile,
        tablet: typographyHeadingMediumLetterSpacingTablet,
      },
    },
    large: {
      fontSize: {
        mobile: typographyHeadingLargeFontSizeMobile,
        desktop: typographyHeadingLargeFontSizeDesktop,
        tablet: typographyHeadingLargeFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingLargeLineHeightMobile,
        desktop: typographyHeadingLargeLineHeightDesktop,
        tablet: typographyHeadingLargeLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingLargeLetterSpacingDesktop,
        mobile: typographyHeadingLargeLetterSpacingMobile,
        tablet: typographyHeadingLargeLetterSpacingTablet,
      },
    },
    xlarge: {
      fontSize: {
        mobile: typographyHeadingXlargeFontSizeMobile,
        desktop: typographyHeadingXlargeFontSizeDesktop,
        tablet: typographyHeadingXlargeFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingXlargeLineHeightMobile,
        desktop: typographyHeadingXlargeLineHeightDesktop,
        tablet: typographyHeadingXlargeLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingXlargeLetterSpacingDesktop,
        mobile: typographyHeadingXlargeLetterSpacingMobile,
        tablet: typographyHeadingXlargeLetterSpacingTablet,
      },
    },
  },
};
