/* This file was generated by Supernova, don't change manually */
export const formFieldLargeRadiusDesktop = '8px';
export const formFieldLargeRadiusMobile = '8px';
export const formFieldLargeRadiusTablet = '8px';

export const formFieldMediumRadiusDesktop = '8px';
export const formFieldMediumRadiusMobile = '8px';
export const formFieldMediumRadiusTablet = '8px';

export const formFieldSmallRadiusDesktop = '8px';
export const formFieldSmallRadiusMobile = '8px';
export const formFieldSmallRadiusTablet = '8px';

export const buttonLargeRadiusDesktop = '9999px';
export const buttonLargeRadiusMobile = '9999px';
export const buttonLargeRadiusTablet = '9999px';

export const buttonMediumRadiusDesktop = '9999px';
export const buttonMediumRadiusMobile = '9999px';
export const buttonMediumRadiusTablet = '9999px';

export const buttonSmallRadiusDesktop = '9999px';
export const buttonSmallRadiusMobile = '9999px';
export const buttonSmallRadiusTablet = '9999px';

export const breakpointMobile = 0;
export const breakpointTablet = '768px';
export const breakpointDesktop = '1280px';

export const typographyBodyXsmallFontSizeDesktop = '12px';
export const typographyBodyXsmallFontSizeMobile = '12px';
export const typographyBodyXsmallFontSizeTablet = '12px';

export const typographyBodySmallFontSizeDesktop = '14px';
export const typographyBodySmallFontSizeMobile = '14px';
export const typographyBodySmallFontSizeTablet = '14px';

export const typographyBodyMediumFontSizeDesktop = '16px';
export const typographyBodyMediumFontSizeMobile = '16px';
export const typographyBodyMediumFontSizeTablet = '16px';

export const typographyBodyLargeFontSizeDesktop = '18px';
export const typographyBodyLargeFontSizeMobile = '18px';
export const typographyBodyLargeFontSizeTablet = '18px';

export const typographyHeadingXsmallFontSizeMobile = '18px';

export const typographyBodyXlargeFontSizeDesktop = '20px';
export const typographyBodyXlargeFontSizeMobile = '20px';
export const typographyBodyXlargeFontSizeTablet = '20px';

export const typographyHeadingSmallFontSizeMobile = '20px';

export const typographyHeadingXsmallFontSizeDesktop = '20px';
export const typographyHeadingXsmallFontSizeTablet = '20px';

export const typographyHeadingMediumFontSizeMobile = '24px';

export const typographyHeadingSmallFontSizeDesktop = '24px';
export const typographyHeadingSmallFontSizeTablet = '24px';

export const typographyHeadingLargeFontSizeMobile = '32px';

export const typographyHeadingMediumFontSizeDesktop = '32px';
export const typographyHeadingMediumFontSizeTablet = '32px';

export const typographyHeadingXlargeFontSizeMobile = '36px';

export const typographyHeadingLargeFontSizeDesktop = '40px';
export const typographyHeadingLargeFontSizeTablet = '40px';

export const typographyHeadingXlargeFontSizeDesktop = '48px';
export const typographyHeadingXlargeFontSizeTablet = '48px';

export const typographyBodyXsmallLineHeightDesktop = '16px';
export const typographyBodyXsmallLineHeightMobile = '16px';
export const typographyBodyXsmallLineHeightTablet = '16px';

export const typographyBodySmallLineHeightDesktop = '20px';
export const typographyBodySmallLineHeightMobile = '20px';
export const typographyBodySmallLineHeightTablet = '20px';

export const typographyBodyMediumLineHeightDesktop = '22px';
export const typographyBodyMediumLineHeightMobile = '22px';
export const typographyBodyMediumLineHeightTablet = '22px';

export const typographyHeadingXsmallLineHeightMobile = '22px';

export const typographyBodyLargeLineHeightDesktop = '24px';
export const typographyBodyLargeLineHeightMobile = '24px';
export const typographyBodyLargeLineHeightTablet = '24px';

export const typographyHeadingSmallLineHeightMobile = '24px';

export const typographyHeadingXsmallLineHeightDesktop = '24px';
export const typographyHeadingXsmallLineHeightTablet = '24px';

export const typographyBodyXlargeLineHeightDesktop = '28px';
export const typographyBodyXlargeLineHeightMobile = '28px';
export const typographyBodyXlargeLineHeightTablet = '28px';

export const typographyHeadingMediumLineHeightMobile = '28px';

export const typographyHeadingSmallLineHeightDesktop = '28px';
export const typographyHeadingSmallLineHeightTablet = '28px';

export const typographyHeadingLargeLineHeightMobile = '38px';

export const typographyHeadingMediumLineHeightDesktop = '38px';
export const typographyHeadingMediumLineHeightTablet = '38px';

export const typographyHeadingXlargeLineHeightMobile = '42px';

export const typographyHeadingLargeLineHeightDesktop = '48px';
export const typographyHeadingLargeLineHeightTablet = '48px';

export const typographyHeadingXlargeLineHeightDesktop = '58px';
export const typographyHeadingXlargeLineHeightTablet = '58px';

export const typographyBodyLargeLetterSpacingDesktop = 0;
export const typographyBodyLargeLetterSpacingMobile = 0;
export const typographyBodyLargeLetterSpacingTablet = 0;

export const typographyBodyMediumLetterSpacingDesktop = 0;
export const typographyBodyMediumLetterSpacingMobile = 0;
export const typographyBodyMediumLetterSpacingTablet = 0;

export const typographyBodySmallLetterSpacingDesktop = 0;
export const typographyBodySmallLetterSpacingMobile = 0;
export const typographyBodySmallLetterSpacingTablet = 0;

export const typographyBodyXlargeLetterSpacingDesktop = 0;
export const typographyBodyXlargeLetterSpacingMobile = 0;
export const typographyBodyXlargeLetterSpacingTablet = 0;

export const typographyBodyXsmallLetterSpacingDesktop = 0;
export const typographyBodyXsmallLetterSpacingMobile = 0;
export const typographyBodyXsmallLetterSpacingTablet = 0;

export const typographyHeadingLargeLetterSpacingDesktop = 0;
export const typographyHeadingLargeLetterSpacingMobile = 0;
export const typographyHeadingLargeLetterSpacingTablet = 0;

export const typographyHeadingMediumLetterSpacingDesktop = 0;
export const typographyHeadingMediumLetterSpacingMobile = 0;
export const typographyHeadingMediumLetterSpacingTablet = 0;

export const typographyHeadingSmallLetterSpacingDesktop = 0;
export const typographyHeadingSmallLetterSpacingMobile = 0;
export const typographyHeadingSmallLetterSpacingTablet = 0;

export const typographyHeadingXlargeLetterSpacingDesktop = 0;
export const typographyHeadingXlargeLetterSpacingMobile = 0;
export const typographyHeadingXlargeLetterSpacingTablet = 0;

export const typographyHeadingXsmallLetterSpacingDesktop = 0;
export const typographyHeadingXsmallLetterSpacingMobile = 0;
export const typographyHeadingXsmallLetterSpacingTablet = 0;

export const formFields = {
  large: {
    radius: {
      desktop: formFieldLargeRadiusDesktop,
      mobile: formFieldLargeRadiusMobile,
      tablet: formFieldLargeRadiusTablet,
    },
  },
  medium: {
    radius: {
      desktop: formFieldMediumRadiusDesktop,
      mobile: formFieldMediumRadiusMobile,
      tablet: formFieldMediumRadiusTablet,
    },
  },
  small: {
    radius: {
      desktop: formFieldSmallRadiusDesktop,
      mobile: formFieldSmallRadiusMobile,
      tablet: formFieldSmallRadiusTablet,
    },
  },
};

export const buttons = {
  large: {
    radius: {
      desktop: buttonLargeRadiusDesktop,
      mobile: buttonLargeRadiusMobile,
      tablet: buttonLargeRadiusTablet,
    },
  },
  medium: {
    radius: {
      desktop: buttonMediumRadiusDesktop,
      mobile: buttonMediumRadiusMobile,
      tablet: buttonMediumRadiusTablet,
    },
  },
  small: {
    radius: {
      desktop: buttonSmallRadiusDesktop,
      mobile: buttonSmallRadiusMobile,
      tablet: buttonSmallRadiusTablet,
    },
  },
};

export const breakpoints = {
  mobile: breakpointMobile,
  tablet: breakpointTablet,
  desktop: breakpointDesktop,
};

export const typographys = {
  body: {
    xsmall: {
      fontSize: {
        desktop: typographyBodyXsmallFontSizeDesktop,
        mobile: typographyBodyXsmallFontSizeMobile,
        tablet: typographyBodyXsmallFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodyXsmallLineHeightDesktop,
        mobile: typographyBodyXsmallLineHeightMobile,
        tablet: typographyBodyXsmallLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodyXsmallLetterSpacingDesktop,
        mobile: typographyBodyXsmallLetterSpacingMobile,
        tablet: typographyBodyXsmallLetterSpacingTablet,
      },
    },
    small: {
      fontSize: {
        desktop: typographyBodySmallFontSizeDesktop,
        mobile: typographyBodySmallFontSizeMobile,
        tablet: typographyBodySmallFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodySmallLineHeightDesktop,
        mobile: typographyBodySmallLineHeightMobile,
        tablet: typographyBodySmallLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodySmallLetterSpacingDesktop,
        mobile: typographyBodySmallLetterSpacingMobile,
        tablet: typographyBodySmallLetterSpacingTablet,
      },
    },
    medium: {
      fontSize: {
        desktop: typographyBodyMediumFontSizeDesktop,
        mobile: typographyBodyMediumFontSizeMobile,
        tablet: typographyBodyMediumFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodyMediumLineHeightDesktop,
        mobile: typographyBodyMediumLineHeightMobile,
        tablet: typographyBodyMediumLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodyMediumLetterSpacingDesktop,
        mobile: typographyBodyMediumLetterSpacingMobile,
        tablet: typographyBodyMediumLetterSpacingTablet,
      },
    },
    large: {
      fontSize: {
        desktop: typographyBodyLargeFontSizeDesktop,
        mobile: typographyBodyLargeFontSizeMobile,
        tablet: typographyBodyLargeFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodyLargeLineHeightDesktop,
        mobile: typographyBodyLargeLineHeightMobile,
        tablet: typographyBodyLargeLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodyLargeLetterSpacingDesktop,
        mobile: typographyBodyLargeLetterSpacingMobile,
        tablet: typographyBodyLargeLetterSpacingTablet,
      },
    },
    xlarge: {
      fontSize: {
        desktop: typographyBodyXlargeFontSizeDesktop,
        mobile: typographyBodyXlargeFontSizeMobile,
        tablet: typographyBodyXlargeFontSizeTablet,
      },
      lineHeight: {
        desktop: typographyBodyXlargeLineHeightDesktop,
        mobile: typographyBodyXlargeLineHeightMobile,
        tablet: typographyBodyXlargeLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyBodyXlargeLetterSpacingDesktop,
        mobile: typographyBodyXlargeLetterSpacingMobile,
        tablet: typographyBodyXlargeLetterSpacingTablet,
      },
    },
  },
  heading: {
    xsmall: {
      fontSize: {
        mobile: typographyHeadingXsmallFontSizeMobile,
        desktop: typographyHeadingXsmallFontSizeDesktop,
        tablet: typographyHeadingXsmallFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingXsmallLineHeightMobile,
        desktop: typographyHeadingXsmallLineHeightDesktop,
        tablet: typographyHeadingXsmallLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingXsmallLetterSpacingDesktop,
        mobile: typographyHeadingXsmallLetterSpacingMobile,
        tablet: typographyHeadingXsmallLetterSpacingTablet,
      },
    },
    small: {
      fontSize: {
        mobile: typographyHeadingSmallFontSizeMobile,
        desktop: typographyHeadingSmallFontSizeDesktop,
        tablet: typographyHeadingSmallFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingSmallLineHeightMobile,
        desktop: typographyHeadingSmallLineHeightDesktop,
        tablet: typographyHeadingSmallLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingSmallLetterSpacingDesktop,
        mobile: typographyHeadingSmallLetterSpacingMobile,
        tablet: typographyHeadingSmallLetterSpacingTablet,
      },
    },
    medium: {
      fontSize: {
        mobile: typographyHeadingMediumFontSizeMobile,
        desktop: typographyHeadingMediumFontSizeDesktop,
        tablet: typographyHeadingMediumFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingMediumLineHeightMobile,
        desktop: typographyHeadingMediumLineHeightDesktop,
        tablet: typographyHeadingMediumLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingMediumLetterSpacingDesktop,
        mobile: typographyHeadingMediumLetterSpacingMobile,
        tablet: typographyHeadingMediumLetterSpacingTablet,
      },
    },
    large: {
      fontSize: {
        mobile: typographyHeadingLargeFontSizeMobile,
        desktop: typographyHeadingLargeFontSizeDesktop,
        tablet: typographyHeadingLargeFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingLargeLineHeightMobile,
        desktop: typographyHeadingLargeLineHeightDesktop,
        tablet: typographyHeadingLargeLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingLargeLetterSpacingDesktop,
        mobile: typographyHeadingLargeLetterSpacingMobile,
        tablet: typographyHeadingLargeLetterSpacingTablet,
      },
    },
    xlarge: {
      fontSize: {
        mobile: typographyHeadingXlargeFontSizeMobile,
        desktop: typographyHeadingXlargeFontSizeDesktop,
        tablet: typographyHeadingXlargeFontSizeTablet,
      },
      lineHeight: {
        mobile: typographyHeadingXlargeLineHeightMobile,
        desktop: typographyHeadingXlargeLineHeightDesktop,
        tablet: typographyHeadingXlargeLineHeightTablet,
      },
      letterSpacing: {
        desktop: typographyHeadingXlargeLetterSpacingDesktop,
        mobile: typographyHeadingXlargeLetterSpacingMobile,
        tablet: typographyHeadingXlargeLetterSpacingTablet,
      },
    },
  },
};
