/* This file was generated by Supernova, don't change manually */
export const accent01BackgroundBasic = 'var(--spirit-color-accent-01-background-basic)';
export const accent01BackgroundSubtle = 'var(--spirit-color-accent-01-background-subtle)';
export const accent01BorderBasic = 'var(--spirit-color-accent-01-border-basic)';
export const accent01BorderSubtle = 'var(--spirit-color-accent-01-border-subtle)';
export const accent01ContentBasic = 'var(--spirit-color-accent-01-content-basic)';
export const accent01ContentSubtle = 'var(--spirit-color-accent-01-content-subtle)';
export const accent01StateActive = 'var(--spirit-color-accent-01-state-active)';
export const accent01StateDefault = 'var(--spirit-color-accent-01-state-default)';
export const accent01StateHover = 'var(--spirit-color-accent-01-state-hover)';

export const accent02BackgroundBasic = 'var(--spirit-color-accent-02-background-basic)';
export const accent02BackgroundSubtle = 'var(--spirit-color-accent-02-background-subtle)';
export const accent02BorderBasic = 'var(--spirit-color-accent-02-border-basic)';
export const accent02BorderSubtle = 'var(--spirit-color-accent-02-border-subtle)';
export const accent02ContentBasic = 'var(--spirit-color-accent-02-content-basic)';
export const accent02ContentSubtle = 'var(--spirit-color-accent-02-content-subtle)';
export const accent02StateActive = 'var(--spirit-color-accent-02-state-active)';
export const accent02StateDefault = 'var(--spirit-color-accent-02-state-default)';
export const accent02StateHover = 'var(--spirit-color-accent-02-state-hover)';

export const accent03BackgroundBasic = 'var(--spirit-color-accent-03-background-basic)';
export const accent03BackgroundSubtle = 'var(--spirit-color-accent-03-background-subtle)';
export const accent03BorderBasic = 'var(--spirit-color-accent-03-border-basic)';
export const accent03BorderSubtle = 'var(--spirit-color-accent-03-border-subtle)';
export const accent03ContentBasic = 'var(--spirit-color-accent-03-content-basic)';
export const accent03ContentSubtle = 'var(--spirit-color-accent-03-content-subtle)';
export const accent03StateActive = 'var(--spirit-color-accent-03-state-active)';
export const accent03StateDefault = 'var(--spirit-color-accent-03-state-default)';
export const accent03StateHover = 'var(--spirit-color-accent-03-state-hover)';

export const accent04BackgroundBasic = 'var(--spirit-color-accent-04-background-basic)';
export const accent04BackgroundSubtle = 'var(--spirit-color-accent-04-background-subtle)';
export const accent04BorderBasic = 'var(--spirit-color-accent-04-border-basic)';
export const accent04BorderSubtle = 'var(--spirit-color-accent-04-border-subtle)';
export const accent04ContentBasic = 'var(--spirit-color-accent-04-content-basic)';
export const accent04ContentSubtle = 'var(--spirit-color-accent-04-content-subtle)';
export const accent04StateActive = 'var(--spirit-color-accent-04-state-active)';
export const accent04StateDefault = 'var(--spirit-color-accent-04-state-default)';
export const accent04StateHover = 'var(--spirit-color-accent-04-state-hover)';

export const accent05BackgroundBasic = 'var(--spirit-color-accent-05-background-basic)';
export const accent05BackgroundSubtle = 'var(--spirit-color-accent-05-background-subtle)';
export const accent05BorderBasic = 'var(--spirit-color-accent-05-border-basic)';
export const accent05BorderSubtle = 'var(--spirit-color-accent-05-border-subtle)';
export const accent05ContentBasic = 'var(--spirit-color-accent-05-content-basic)';
export const accent05ContentSubtle = 'var(--spirit-color-accent-05-content-subtle)';
export const accent05StateActive = 'var(--spirit-color-accent-05-state-active)';
export const accent05StateDefault = 'var(--spirit-color-accent-05-state-default)';
export const accent05StateHover = 'var(--spirit-color-accent-05-state-hover)';

export const accent06BackgroundBasic = 'var(--spirit-color-accent-06-background-basic)';
export const accent06BackgroundSubtle = 'var(--spirit-color-accent-06-background-subtle)';
export const accent06BorderBasic = 'var(--spirit-color-accent-06-border-basic)';
export const accent06BorderSubtle = 'var(--spirit-color-accent-06-border-subtle)';
export const accent06ContentBasic = 'var(--spirit-color-accent-06-content-basic)';
export const accent06ContentSubtle = 'var(--spirit-color-accent-06-content-subtle)';
export const accent06StateActive = 'var(--spirit-color-accent-06-state-active)';
export const accent06StateDefault = 'var(--spirit-color-accent-06-state-default)';
export const accent06StateHover = 'var(--spirit-color-accent-06-state-hover)';

export const backgroundBackdrop = 'var(--spirit-color-background-backdrop)';

export const backgroundInteractiveStateActive = 'var(--spirit-color-background-interactive-state-active)';
export const backgroundInteractiveStateDefault = 'var(--spirit-color-background-interactive-state-default)';
export const backgroundInteractiveStateHover = 'var(--spirit-color-background-interactive-state-hover)';

export const backgroundPrimary = 'var(--spirit-color-background-primary)';
export const backgroundSecondary = 'var(--spirit-color-background-secondary)';
export const backgroundTertiary = 'var(--spirit-color-background-tertiary)';

export const borderBasic = 'var(--spirit-color-border-basic)';
export const borderFocus = 'var(--spirit-color-border-focus)';

export const borderInteractiveStateActive = 'var(--spirit-color-border-interactive-state-active)';
export const borderInteractiveStateDefault = 'var(--spirit-color-border-interactive-state-default)';
export const borderInteractiveStateHover = 'var(--spirit-color-border-interactive-state-hover)';
export const borderInteractiveStateSelected = 'var(--spirit-color-border-interactive-state-selected)';

export const componentButtonPlainBorder = 'var(--spirit-color-component-button-plain-border)';
export const componentButtonPlainContent = 'var(--spirit-color-component-button-plain-content)';
export const componentButtonPlainStateActive = 'var(--spirit-color-component-button-plain-state-active)';
export const componentButtonPlainStateDefault = 'var(--spirit-color-component-button-plain-state-default)';
export const componentButtonPlainStateHover = 'var(--spirit-color-component-button-plain-state-hover)';

export const componentButtonPrimaryBorder = 'var(--spirit-color-component-button-primary-border)';
export const componentButtonPrimaryContent = 'var(--spirit-color-component-button-primary-content)';
export const componentButtonPrimaryStateActive = 'var(--spirit-color-component-button-primary-state-active)';
export const componentButtonPrimaryStateDefault = 'var(--spirit-color-component-button-primary-state-default)';
export const componentButtonPrimaryStateHover = 'var(--spirit-color-component-button-primary-state-hover)';

export const componentButtonSecondaryBorder = 'var(--spirit-color-component-button-secondary-border)';
export const componentButtonSecondaryContent = 'var(--spirit-color-component-button-secondary-content)';
export const componentButtonSecondaryStateActive = 'var(--spirit-color-component-button-secondary-state-active)';
export const componentButtonSecondaryStateDefault = 'var(--spirit-color-component-button-secondary-state-default)';
export const componentButtonSecondaryStateHover = 'var(--spirit-color-component-button-secondary-state-hover)';

export const componentButtonTertiaryBorder = 'var(--spirit-color-component-button-tertiary-border)';
export const componentButtonTertiaryContent = 'var(--spirit-color-component-button-tertiary-content)';
export const componentButtonTertiaryStateActive = 'var(--spirit-color-component-button-tertiary-state-active)';
export const componentButtonTertiaryStateDefault = 'var(--spirit-color-component-button-tertiary-state-default)';
export const componentButtonTertiaryStateHover = 'var(--spirit-color-component-button-tertiary-state-hover)';

export const componentHeaderBackground = 'var(--spirit-color-component-header-background)';
export const componentHeaderBorder = 'var(--spirit-color-component-header-border)';

export const componentNavigationItemBackgroundStateActive = 'var(--spirit-color-component-navigation-item-background-state-active)';
export const componentNavigationItemBackgroundStateDefault = 'var(--spirit-color-component-navigation-item-background-state-default)';
export const componentNavigationItemBackgroundStateHover = 'var(--spirit-color-component-navigation-item-background-state-hover)';
export const componentNavigationItemBackgroundStateSelected = 'var(--spirit-color-component-navigation-item-background-state-selected)';
export const componentNavigationItemStateActive = 'var(--spirit-color-component-navigation-item-state-active)';
export const componentNavigationItemStateDefault = 'var(--spirit-color-component-navigation-item-state-default)';
export const componentNavigationItemStateHover = 'var(--spirit-color-component-navigation-item-state-hover)';
export const componentNavigationItemStateSelected = 'var(--spirit-color-component-navigation-item-state-selected)';
export const componentNavigationItemStripeStateSelected = 'var(--spirit-color-component-navigation-item-stripe-state-selected)';
export const componentNavigationItemStripeStateUnselected = 'var(--spirit-color-component-navigation-item-stripe-state-unselected)';

export const componentPaginationSelectedBorder = 'var(--spirit-color-component-pagination-selected-border)';
export const componentPaginationSelectedContent = 'var(--spirit-color-component-pagination-selected-content)';
export const componentPaginationSelectedStateActive = 'var(--spirit-color-component-pagination-selected-state-active)';
export const componentPaginationSelectedStateDefault = 'var(--spirit-color-component-pagination-selected-state-default)';
export const componentPaginationSelectedStateHover = 'var(--spirit-color-component-pagination-selected-state-hover)';
export const componentPaginationUnselectedBorder = 'var(--spirit-color-component-pagination-unselected-border)';
export const componentPaginationUnselectedContent = 'var(--spirit-color-component-pagination-unselected-content)';
export const componentPaginationUnselectedStateActive = 'var(--spirit-color-component-pagination-unselected-state-active)';
export const componentPaginationUnselectedStateDefault = 'var(--spirit-color-component-pagination-unselected-state-default)';
export const componentPaginationUnselectedStateHover = 'var(--spirit-color-component-pagination-unselected-state-hover)';

export const componentPricingPlanHighlightedBackground = 'var(--spirit-color-component-pricing-plan-highlighted-background)';
export const componentPricingPlanHighlightedBorder = 'var(--spirit-color-component-pricing-plan-highlighted-border)';
export const componentPricingPlanHighlightedContent = 'var(--spirit-color-component-pricing-plan-highlighted-content)';

export const componentToggleSelectedBorder = 'var(--spirit-color-component-toggle-selected-border)';
export const componentToggleSelectedContent = 'var(--spirit-color-component-toggle-selected-content)';
export const componentToggleSelectedStateActive = 'var(--spirit-color-component-toggle-selected-state-active)';
export const componentToggleSelectedStateDefault = 'var(--spirit-color-component-toggle-selected-state-default)';
export const componentToggleSelectedStateHover = 'var(--spirit-color-component-toggle-selected-state-hover)';
export const componentToggleUnselectedBorder = 'var(--spirit-color-component-toggle-unselected-border)';
export const componentToggleUnselectedContent = 'var(--spirit-color-component-toggle-unselected-content)';
export const componentToggleUnselectedStateActive = 'var(--spirit-color-component-toggle-unselected-state-active)';
export const componentToggleUnselectedStateDefault = 'var(--spirit-color-component-toggle-unselected-state-default)';
export const componentToggleUnselectedStateHover = 'var(--spirit-color-component-toggle-unselected-state-hover)';

export const disabledBackground = 'var(--spirit-color-disabled-background)';
export const disabledBorder = 'var(--spirit-color-disabled-border)';
export const disabledContent = 'var(--spirit-color-disabled-content)';
export const disabledForeground = 'var(--spirit-color-disabled-foreground)';

export const emotionDangerBackgroundBasic = 'var(--spirit-color-emotion-danger-background-basic)';
export const emotionDangerBackgroundSubtle = 'var(--spirit-color-emotion-danger-background-subtle)';
export const emotionDangerBorderBasic = 'var(--spirit-color-emotion-danger-border-basic)';
export const emotionDangerBorderSubtle = 'var(--spirit-color-emotion-danger-border-subtle)';
export const emotionDangerContentBasic = 'var(--spirit-color-emotion-danger-content-basic)';
export const emotionDangerContentSubtle = 'var(--spirit-color-emotion-danger-content-subtle)';
export const emotionDangerStateActive = 'var(--spirit-color-emotion-danger-state-active)';
export const emotionDangerStateDefault = 'var(--spirit-color-emotion-danger-state-default)';
export const emotionDangerStateHover = 'var(--spirit-color-emotion-danger-state-hover)';

export const emotionInformativeBackgroundBasic = 'var(--spirit-color-emotion-informative-background-basic)';
export const emotionInformativeBackgroundSubtle = 'var(--spirit-color-emotion-informative-background-subtle)';
export const emotionInformativeBorderBasic = 'var(--spirit-color-emotion-informative-border-basic)';
export const emotionInformativeBorderSubtle = 'var(--spirit-color-emotion-informative-border-subtle)';
export const emotionInformativeContentBasic = 'var(--spirit-color-emotion-informative-content-basic)';
export const emotionInformativeContentSubtle = 'var(--spirit-color-emotion-informative-content-subtle)';
export const emotionInformativeStateActive = 'var(--spirit-color-emotion-informative-state-active)';
export const emotionInformativeStateDefault = 'var(--spirit-color-emotion-informative-state-default)';
export const emotionInformativeStateHover = 'var(--spirit-color-emotion-informative-state-hover)';

export const emotionSuccessBackgroundBasic = 'var(--spirit-color-emotion-success-background-basic)';
export const emotionSuccessBackgroundSubtle = 'var(--spirit-color-emotion-success-background-subtle)';
export const emotionSuccessBorderBasic = 'var(--spirit-color-emotion-success-border-basic)';
export const emotionSuccessBorderSubtle = 'var(--spirit-color-emotion-success-border-subtle)';
export const emotionSuccessContentBasic = 'var(--spirit-color-emotion-success-content-basic)';
export const emotionSuccessContentSubtle = 'var(--spirit-color-emotion-success-content-subtle)';
export const emotionSuccessStateActive = 'var(--spirit-color-emotion-success-state-active)';
export const emotionSuccessStateDefault = 'var(--spirit-color-emotion-success-state-default)';
export const emotionSuccessStateHover = 'var(--spirit-color-emotion-success-state-hover)';

export const emotionWarningBackgroundBasic = 'var(--spirit-color-emotion-warning-background-basic)';
export const emotionWarningBackgroundSubtle = 'var(--spirit-color-emotion-warning-background-subtle)';
export const emotionWarningBorderBasic = 'var(--spirit-color-emotion-warning-border-basic)';
export const emotionWarningBorderSubtle = 'var(--spirit-color-emotion-warning-border-subtle)';
export const emotionWarningContentBasic = 'var(--spirit-color-emotion-warning-content-basic)';
export const emotionWarningContentSubtle = 'var(--spirit-color-emotion-warning-content-subtle)';
export const emotionWarningStateActive = 'var(--spirit-color-emotion-warning-state-active)';
export const emotionWarningStateDefault = 'var(--spirit-color-emotion-warning-state-default)';
export const emotionWarningStateHover = 'var(--spirit-color-emotion-warning-state-hover)';

export const focusFocusRingColor01 = 'var(--spirit-color-focus-focus-ring-color-01)';

export const formFieldDanger = 'var(--spirit-color-form-field-danger)';

export const formFieldFillBackgroundStateActive = 'var(--spirit-color-form-field-fill-background-state-active)';
export const formFieldFillBackgroundStateDefault = 'var(--spirit-color-form-field-fill-background-state-default)';
export const formFieldFillBackgroundStateHover = 'var(--spirit-color-form-field-fill-background-state-hover)';
export const formFieldFillBorderStateActive = 'var(--spirit-color-form-field-fill-border-state-active)';
export const formFieldFillBorderStateDefault = 'var(--spirit-color-form-field-fill-border-state-default)';
export const formFieldFillBorderStateHover = 'var(--spirit-color-form-field-fill-border-state-hover)';
export const formFieldFillBorderStateSelected = 'var(--spirit-color-form-field-fill-border-state-selected)';
export const formFieldFillContent = 'var(--spirit-color-form-field-fill-content)';
export const formFieldFillPlaceholder = 'var(--spirit-color-form-field-fill-placeholder)';

export const formFieldHelperText = 'var(--spirit-color-form-field-helper-text)';
export const formFieldLabel = 'var(--spirit-color-form-field-label)';

export const formFieldOutlineBackgroundStateActive = 'var(--spirit-color-form-field-outline-background-state-active)';
export const formFieldOutlineBackgroundStateDefault = 'var(--spirit-color-form-field-outline-background-state-default)';
export const formFieldOutlineBackgroundStateHover = 'var(--spirit-color-form-field-outline-background-state-hover)';
export const formFieldOutlineBorderStateActive = 'var(--spirit-color-form-field-outline-border-state-active)';
export const formFieldOutlineBorderStateDefault = 'var(--spirit-color-form-field-outline-border-state-default)';
export const formFieldOutlineBorderStateHover = 'var(--spirit-color-form-field-outline-border-state-hover)';
export const formFieldOutlineBorderStateSelected = 'var(--spirit-color-form-field-outline-border-state-selected)';
export const formFieldOutlineContent = 'var(--spirit-color-form-field-outline-content)';
export const formFieldOutlinePlaceholder = 'var(--spirit-color-form-field-outline-placeholder)';

export const formFieldSuccess = 'var(--spirit-color-form-field-success)';
export const formFieldWarning = 'var(--spirit-color-form-field-warning)';

export const gradientBasicOverlayColor01 = 'var(--spirit-color-gradient-basic-overlay-color-01)';
export const gradientBasicOverlayColor02 = 'var(--spirit-color-gradient-basic-overlay-color-02)';

export const gradientPrimaryColor01 = 'var(--spirit-color-gradient-primary-color-01)';
export const gradientPrimaryColor02 = 'var(--spirit-color-gradient-primary-color-02)';

export const gradientSecondaryColor01 = 'var(--spirit-color-gradient-secondary-color-01)';
export const gradientSecondaryColor02 = 'var(--spirit-color-gradient-secondary-color-02)';

export const gradientSkeletonColor01 = 'var(--spirit-color-gradient-skeleton-color-01)';
export const gradientSkeletonColor02 = 'var(--spirit-color-gradient-skeleton-color-02)';
export const gradientSkeletonColor03 = 'var(--spirit-color-gradient-skeleton-color-03)';

export const linkPrimaryStateActive = 'var(--spirit-color-link-primary-state-active)';
export const linkPrimaryStateDefault = 'var(--spirit-color-link-primary-state-default)';
export const linkPrimaryStateHover = 'var(--spirit-color-link-primary-state-hover)';

export const linkSecondaryStateActive = 'var(--spirit-color-link-secondary-state-active)';
export const linkSecondaryStateDefault = 'var(--spirit-color-link-secondary-state-default)';
export const linkSecondaryStateHover = 'var(--spirit-color-link-secondary-state-hover)';

export const linkStateVisited = 'var(--spirit-color-link-state-visited)';

export const linkTertiaryStateActive = 'var(--spirit-color-link-tertiary-state-active)';
export const linkTertiaryStateDefault = 'var(--spirit-color-link-tertiary-state-default)';
export const linkTertiaryStateHover = 'var(--spirit-color-link-tertiary-state-hover)';

export const neutralBackgroundBasic = 'var(--spirit-color-neutral-background-basic)';
export const neutralBackgroundSubtle = 'var(--spirit-color-neutral-background-subtle)';
export const neutralBorderBasic = 'var(--spirit-color-neutral-border-basic)';
export const neutralBorderSubtle = 'var(--spirit-color-neutral-border-subtle)';
export const neutralContentBasic = 'var(--spirit-color-neutral-content-basic)';
export const neutralContentSubtle = 'var(--spirit-color-neutral-content-subtle)';
export const neutralStateActive = 'var(--spirit-color-neutral-state-active)';
export const neutralStateDefault = 'var(--spirit-color-neutral-state-default)';
export const neutralStateHover = 'var(--spirit-color-neutral-state-hover)';

export const selectedBackgroundBasic = 'var(--spirit-color-selected-background-basic)';
export const selectedBackgroundSubtle = 'var(--spirit-color-selected-background-subtle)';
export const selectedBorderBasic = 'var(--spirit-color-selected-border-basic)';
export const selectedBorderSubtle = 'var(--spirit-color-selected-border-subtle)';
export const selectedContentBasic = 'var(--spirit-color-selected-content-basic)';
export const selectedContentSubtle = 'var(--spirit-color-selected-content-subtle)';
export const selectedStateActive = 'var(--spirit-color-selected-state-active)';
export const selectedStateDefault = 'var(--spirit-color-selected-state-default)';
export const selectedStateHover = 'var(--spirit-color-selected-state-hover)';

export const shadowShadow100Color01 = 'var(--spirit-color-shadow-shadow-100-color-01)';

export const shadowShadow200Color01 = 'var(--spirit-color-shadow-shadow-200-color-01)';

export const shadowShadow300Color01 = 'var(--spirit-color-shadow-shadow-300-color-01)';

export const shadowShadow400Color01 = 'var(--spirit-color-shadow-shadow-400-color-01)';

export const textPrimary = 'var(--spirit-color-text-primary)';
export const textSecondary = 'var(--spirit-color-text-secondary)';
export const textTertiary = 'var(--spirit-color-text-tertiary)';

export const accentColors = {
  '01': {
    backgroundBasic: accent01BackgroundBasic,
    backgroundSubtle: accent01BackgroundSubtle,
    borderBasic: accent01BorderBasic,
    borderSubtle: accent01BorderSubtle,
    contentBasic: accent01ContentBasic,
    contentSubtle: accent01ContentSubtle,
    stateActive: accent01StateActive,
    stateDefault: accent01StateDefault,
    stateHover: accent01StateHover,
  },
  '02': {
    backgroundBasic: accent02BackgroundBasic,
    backgroundSubtle: accent02BackgroundSubtle,
    borderBasic: accent02BorderBasic,
    borderSubtle: accent02BorderSubtle,
    contentBasic: accent02ContentBasic,
    contentSubtle: accent02ContentSubtle,
    stateActive: accent02StateActive,
    stateDefault: accent02StateDefault,
    stateHover: accent02StateHover,
  },
  '03': {
    backgroundBasic: accent03BackgroundBasic,
    backgroundSubtle: accent03BackgroundSubtle,
    borderBasic: accent03BorderBasic,
    borderSubtle: accent03BorderSubtle,
    contentBasic: accent03ContentBasic,
    contentSubtle: accent03ContentSubtle,
    stateActive: accent03StateActive,
    stateDefault: accent03StateDefault,
    stateHover: accent03StateHover,
  },
  '04': {
    backgroundBasic: accent04BackgroundBasic,
    backgroundSubtle: accent04BackgroundSubtle,
    borderBasic: accent04BorderBasic,
    borderSubtle: accent04BorderSubtle,
    contentBasic: accent04ContentBasic,
    contentSubtle: accent04ContentSubtle,
    stateActive: accent04StateActive,
    stateDefault: accent04StateDefault,
    stateHover: accent04StateHover,
  },
  '05': {
    backgroundBasic: accent05BackgroundBasic,
    backgroundSubtle: accent05BackgroundSubtle,
    borderBasic: accent05BorderBasic,
    borderSubtle: accent05BorderSubtle,
    contentBasic: accent05ContentBasic,
    contentSubtle: accent05ContentSubtle,
    stateActive: accent05StateActive,
    stateDefault: accent05StateDefault,
    stateHover: accent05StateHover,
  },
  '06': {
    backgroundBasic: accent06BackgroundBasic,
    backgroundSubtle: accent06BackgroundSubtle,
    borderBasic: accent06BorderBasic,
    borderSubtle: accent06BorderSubtle,
    contentBasic: accent06ContentBasic,
    contentSubtle: accent06ContentSubtle,
    stateActive: accent06StateActive,
    stateDefault: accent06StateDefault,
    stateHover: accent06StateHover,
  },
};

export const backgroundColors = {
  backdrop: backgroundBackdrop,
  interactive: {
    stateActive: backgroundInteractiveStateActive,
    stateDefault: backgroundInteractiveStateDefault,
    stateHover: backgroundInteractiveStateHover,
  },
  primary: backgroundPrimary,
  secondary: backgroundSecondary,
  tertiary: backgroundTertiary,
};

export const borderColors = {
  basic: borderBasic,
  focus: borderFocus,
  interactive: {
    stateActive: borderInteractiveStateActive,
    stateDefault: borderInteractiveStateDefault,
    stateHover: borderInteractiveStateHover,
    stateSelected: borderInteractiveStateSelected,
  },
};

export const componentColors = {
  button: {
    plain: {
      border: componentButtonPlainBorder,
      content: componentButtonPlainContent,
      stateActive: componentButtonPlainStateActive,
      stateDefault: componentButtonPlainStateDefault,
      stateHover: componentButtonPlainStateHover,
    },
    primary: {
      border: componentButtonPrimaryBorder,
      content: componentButtonPrimaryContent,
      stateActive: componentButtonPrimaryStateActive,
      stateDefault: componentButtonPrimaryStateDefault,
      stateHover: componentButtonPrimaryStateHover,
    },
    secondary: {
      border: componentButtonSecondaryBorder,
      content: componentButtonSecondaryContent,
      stateActive: componentButtonSecondaryStateActive,
      stateDefault: componentButtonSecondaryStateDefault,
      stateHover: componentButtonSecondaryStateHover,
    },
    tertiary: {
      border: componentButtonTertiaryBorder,
      content: componentButtonTertiaryContent,
      stateActive: componentButtonTertiaryStateActive,
      stateDefault: componentButtonTertiaryStateDefault,
      stateHover: componentButtonTertiaryStateHover,
    },
  },
  header: {
    background: componentHeaderBackground,
    border: componentHeaderBorder,
  },
  navigation: {
    itemBackgroundStateActive: componentNavigationItemBackgroundStateActive,
    itemBackgroundStateDefault: componentNavigationItemBackgroundStateDefault,
    itemBackgroundStateHover: componentNavigationItemBackgroundStateHover,
    itemBackgroundStateSelected: componentNavigationItemBackgroundStateSelected,
    itemStateActive: componentNavigationItemStateActive,
    itemStateDefault: componentNavigationItemStateDefault,
    itemStateHover: componentNavigationItemStateHover,
    itemStateSelected: componentNavigationItemStateSelected,
    itemStripeStateSelected: componentNavigationItemStripeStateSelected,
    itemStripeStateUnselected: componentNavigationItemStripeStateUnselected,
  },
  pagination: {
    selectedBorder: componentPaginationSelectedBorder,
    selectedContent: componentPaginationSelectedContent,
    selectedStateActive: componentPaginationSelectedStateActive,
    selectedStateDefault: componentPaginationSelectedStateDefault,
    selectedStateHover: componentPaginationSelectedStateHover,
    unselectedBorder: componentPaginationUnselectedBorder,
    unselectedContent: componentPaginationUnselectedContent,
    unselectedStateActive: componentPaginationUnselectedStateActive,
    unselectedStateDefault: componentPaginationUnselectedStateDefault,
    unselectedStateHover: componentPaginationUnselectedStateHover,
  },
  pricingPlan: {
    highlightedBackground: componentPricingPlanHighlightedBackground,
    highlightedBorder: componentPricingPlanHighlightedBorder,
    highlightedContent: componentPricingPlanHighlightedContent,
  },
  toggle: {
    selectedBorder: componentToggleSelectedBorder,
    selectedContent: componentToggleSelectedContent,
    selectedStateActive: componentToggleSelectedStateActive,
    selectedStateDefault: componentToggleSelectedStateDefault,
    selectedStateHover: componentToggleSelectedStateHover,
    unselectedBorder: componentToggleUnselectedBorder,
    unselectedContent: componentToggleUnselectedContent,
    unselectedStateActive: componentToggleUnselectedStateActive,
    unselectedStateDefault: componentToggleUnselectedStateDefault,
    unselectedStateHover: componentToggleUnselectedStateHover,
  },
};

export const disabledColors = {
  background: disabledBackground,
  border: disabledBorder,
  content: disabledContent,
  foreground: disabledForeground,
};

export const emotionColors = {
  danger: {
    backgroundBasic: emotionDangerBackgroundBasic,
    backgroundSubtle: emotionDangerBackgroundSubtle,
    borderBasic: emotionDangerBorderBasic,
    borderSubtle: emotionDangerBorderSubtle,
    contentBasic: emotionDangerContentBasic,
    contentSubtle: emotionDangerContentSubtle,
    stateActive: emotionDangerStateActive,
    stateDefault: emotionDangerStateDefault,
    stateHover: emotionDangerStateHover,
  },
  informative: {
    backgroundBasic: emotionInformativeBackgroundBasic,
    backgroundSubtle: emotionInformativeBackgroundSubtle,
    borderBasic: emotionInformativeBorderBasic,
    borderSubtle: emotionInformativeBorderSubtle,
    contentBasic: emotionInformativeContentBasic,
    contentSubtle: emotionInformativeContentSubtle,
    stateActive: emotionInformativeStateActive,
    stateDefault: emotionInformativeStateDefault,
    stateHover: emotionInformativeStateHover,
  },
  success: {
    backgroundBasic: emotionSuccessBackgroundBasic,
    backgroundSubtle: emotionSuccessBackgroundSubtle,
    borderBasic: emotionSuccessBorderBasic,
    borderSubtle: emotionSuccessBorderSubtle,
    contentBasic: emotionSuccessContentBasic,
    contentSubtle: emotionSuccessContentSubtle,
    stateActive: emotionSuccessStateActive,
    stateDefault: emotionSuccessStateDefault,
    stateHover: emotionSuccessStateHover,
  },
  warning: {
    backgroundBasic: emotionWarningBackgroundBasic,
    backgroundSubtle: emotionWarningBackgroundSubtle,
    borderBasic: emotionWarningBorderBasic,
    borderSubtle: emotionWarningBorderSubtle,
    contentBasic: emotionWarningContentBasic,
    contentSubtle: emotionWarningContentSubtle,
    stateActive: emotionWarningStateActive,
    stateDefault: emotionWarningStateDefault,
    stateHover: emotionWarningStateHover,
  },
};

export const focusColors = {
  focusRing: {
    color01: focusFocusRingColor01,
  },
};

export const formFieldColors = {
  danger: formFieldDanger,
  fill: {
    backgroundStateActive: formFieldFillBackgroundStateActive,
    backgroundStateDefault: formFieldFillBackgroundStateDefault,
    backgroundStateHover: formFieldFillBackgroundStateHover,
    borderStateActive: formFieldFillBorderStateActive,
    borderStateDefault: formFieldFillBorderStateDefault,
    borderStateHover: formFieldFillBorderStateHover,
    borderStateSelected: formFieldFillBorderStateSelected,
    content: formFieldFillContent,
    placeholder: formFieldFillPlaceholder,
  },
  helperText: formFieldHelperText,
  label: formFieldLabel,
  outline: {
    backgroundStateActive: formFieldOutlineBackgroundStateActive,
    backgroundStateDefault: formFieldOutlineBackgroundStateDefault,
    backgroundStateHover: formFieldOutlineBackgroundStateHover,
    borderStateActive: formFieldOutlineBorderStateActive,
    borderStateDefault: formFieldOutlineBorderStateDefault,
    borderStateHover: formFieldOutlineBorderStateHover,
    borderStateSelected: formFieldOutlineBorderStateSelected,
    content: formFieldOutlineContent,
    placeholder: formFieldOutlinePlaceholder,
  },
  success: formFieldSuccess,
  warning: formFieldWarning,
};

export const gradientColors = {
  basicOverlay: {
    color01: gradientBasicOverlayColor01,
    color02: gradientBasicOverlayColor02,
  },
  primary: {
    color01: gradientPrimaryColor01,
    color02: gradientPrimaryColor02,
  },
  secondary: {
    color01: gradientSecondaryColor01,
    color02: gradientSecondaryColor02,
  },
  skeleton: {
    color01: gradientSkeletonColor01,
    color02: gradientSkeletonColor02,
    color03: gradientSkeletonColor03,
  },
};

export const linkColors = {
  primary: {
    stateActive: linkPrimaryStateActive,
    stateDefault: linkPrimaryStateDefault,
    stateHover: linkPrimaryStateHover,
  },
  secondary: {
    stateActive: linkSecondaryStateActive,
    stateDefault: linkSecondaryStateDefault,
    stateHover: linkSecondaryStateHover,
  },
  stateVisited: linkStateVisited,
  tertiary: {
    stateActive: linkTertiaryStateActive,
    stateDefault: linkTertiaryStateDefault,
    stateHover: linkTertiaryStateHover,
  },
};

export const neutralColors = {
  backgroundBasic: neutralBackgroundBasic,
  backgroundSubtle: neutralBackgroundSubtle,
  borderBasic: neutralBorderBasic,
  borderSubtle: neutralBorderSubtle,
  contentBasic: neutralContentBasic,
  contentSubtle: neutralContentSubtle,
  stateActive: neutralStateActive,
  stateDefault: neutralStateDefault,
  stateHover: neutralStateHover,
};

export const selectedColors = {
  backgroundBasic: selectedBackgroundBasic,
  backgroundSubtle: selectedBackgroundSubtle,
  borderBasic: selectedBorderBasic,
  borderSubtle: selectedBorderSubtle,
  contentBasic: selectedContentBasic,
  contentSubtle: selectedContentSubtle,
  stateActive: selectedStateActive,
  stateDefault: selectedStateDefault,
  stateHover: selectedStateHover,
};

export const shadowColors = {
  shadow100: {
    color01: shadowShadow100Color01,
  },
  shadow200: {
    color01: shadowShadow200Color01,
  },
  shadow300: {
    color01: shadowShadow300Color01,
  },
  shadow400: {
    color01: shadowShadow400Color01,
  },
};

export const textColors = {
  primary: textPrimary,
  secondary: textSecondary,
  tertiary: textTertiary,
};

export const colors = {
  accent: accentColors,
  background: backgroundColors,
  border: borderColors,
  component: componentColors,
  disabled: disabledColors,
  emotion: emotionColors,
  focus: focusColors,
  formField: formFieldColors,
  gradient: gradientColors,
  link: linkColors,
  neutral: neutralColors,
  selected: selectedColors,
  shadow: shadowColors,
  text: textColors,
};
