import { SNAPSHOT_SCHEMA_VERSION } from '../src/snapshot/types.ts';

const white = { r: 1, g: 1, b: 1, a: 1 };
const black = { r: 0, g: 0, b: 0, a: 0.1 };
const accent = { r: 0.847, g: 0, b: 0.565, a: 1 };
const accentOnBrand = { r: 1, g: 1, b: 1, a: 1 };

export const fontStacks = {
  Inter: "'Inter', sans-serif",
};

export const createSnapshot = () => ({
  schemaVersion: SNAPSHOT_SCHEMA_VERSION,
  capturedAt: '2026-08-25T12:00:00.000Z',
  file: { key: 'BXRF3VABXQm2TGkL0nwS4i', name: 'SPIRIT Config' },
  collections: [
    {
      id: 'global',
      name: 'Global tokens',
      key: 'global-key',
      hiddenFromPublishing: false,
      defaultModeId: 'global-default',
      modes: [{ id: 'global-default', name: 'Value' }],
      variableIds: ['border', 'radius', 'radius-full', 'space', 'columns', 'prefix', 'figma-hidden', 'alias-color'],
    },
    {
      id: 'theme',
      name: 'Theme tokens',
      key: 'theme-key',
      hiddenFromPublishing: false,
      defaultModeId: 'theme-default',
      modes: [
        { id: 'theme-default', name: 'theme-light-default' },
        { id: 'theme-on-brand', name: 'theme-light-on-brand' },
      ],
      variableIds: ['accent', 'text'],
    },
    {
      id: 'device',
      name: 'Device',
      key: 'device-key',
      hiddenFromPublishing: false,
      defaultModeId: 'device-mobile',
      modes: [
        { id: 'device-mobile', name: 'mobile' },
        { id: 'device-tablet', name: 'tablet' },
        { id: 'device-desktop', name: 'desktop' },
      ],
      variableIds: ['breakpoint', 'font-size-base', 'font-family-body'],
    },
  ],
  variables: [
    {
      id: 'border',
      name: 'border/width-100',
      key: 'border',
      collectionId: 'global',
      resolvedType: 'FLOAT',
      valuesByMode: { 'global-default': 1 },
      scopes: ['STROKE_FLOAT'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'radius',
      name: 'radius/radius-100',
      key: 'radius',
      collectionId: 'global',
      resolvedType: 'FLOAT',
      valuesByMode: { 'global-default': 2 },
      scopes: ['CORNER_RADIUS'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'radius-full',
      name: 'radius/radius-full',
      key: 'radius-full',
      collectionId: 'global',
      resolvedType: 'FLOAT',
      valuesByMode: { 'global-default': 9999 },
      scopes: ['CORNER_RADIUS'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'space',
      name: 'spacing/space-700',
      key: 'space',
      collectionId: 'global',
      resolvedType: 'FLOAT',
      valuesByMode: { 'global-default': 16 },
      scopes: ['GAP'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'columns',
      name: 'grid/Columns',
      key: 'columns',
      collectionId: 'global',
      resolvedType: 'STRING',
      valuesByMode: { 'global-default': '12' },
      scopes: ['ALL_SCOPES'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'prefix',
      name: 'css-variable-prefix',
      key: 'prefix',
      collectionId: 'global',
      resolvedType: 'STRING',
      valuesByMode: { 'global-default': 'spirit-' },
      scopes: ['ALL_SCOPES'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'figma-hidden',
      name: 'figma-hidden',
      key: 'figma-hidden',
      collectionId: 'global',
      resolvedType: 'STRING',
      valuesByMode: { 'global-default': 'nope' },
      scopes: ['ALL_SCOPES'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'alias-color',
      name: 'Shadow/shadow-100-color-01',
      key: 'alias-color',
      collectionId: 'global',
      resolvedType: 'COLOR',
      valuesByMode: { 'global-default': { type: 'VARIABLE_ALIAS', id: 'remote-color' } },
      scopes: ['ALL_FILLS'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'accent',
      name: 'accent/01/background-basic',
      key: 'accent',
      collectionId: 'theme',
      resolvedType: 'COLOR',
      valuesByMode: { 'theme-default': accent, 'theme-on-brand': accentOnBrand },
      scopes: ['ALL_FILLS'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'text',
      name: 'text/primary',
      key: 'text',
      collectionId: 'theme',
      resolvedType: 'COLOR',
      valuesByMode: { 'theme-default': { r: 0.125, g: 0.125, b: 0.125, a: 1 }, 'theme-on-brand': white },
      scopes: ['ALL_FILLS'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'breakpoint',
      name: 'breakpoint',
      key: 'breakpoint',
      collectionId: 'device',
      resolvedType: 'FLOAT',
      valuesByMode: { 'device-mobile': 375, 'device-tablet': 768, 'device-desktop': 1280 },
      scopes: ['WIDTH_HEIGHT'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'font-size-base',
      name: 'font-size-base',
      key: 'font-size-base',
      collectionId: 'device',
      resolvedType: 'FLOAT',
      valuesByMode: { 'device-mobile': 16, 'device-tablet': 16, 'device-desktop': 16 },
      scopes: ['FONT_SIZE'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'font-family-body',
      name: 'typography/font-family/Body',
      key: 'font-family-body',
      collectionId: 'device',
      resolvedType: 'STRING',
      valuesByMode: { 'device-mobile': 'Inter', 'device-tablet': 'Inter', 'device-desktop': 'Inter' },
      scopes: ['FONT_FAMILY'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
  ],
  styles: [
    {
      type: 'TEXT',
      id: 'text-style',
      name: 'Body/Large/Bold',
      key: 'text-style',
      remote: false,
      fontSize: 18,
      fontName: { family: 'Inter', style: 'Bold' },
      fontWeight: 700,
      letterSpacing: { unit: 'PIXELS', value: 0 },
      lineHeight: { unit: 'PIXELS', value: 28 },
    },
    {
      type: 'TEXT',
      id: 'italic-style',
      name: 'Body/Large/Italic',
      key: 'italic-style',
      remote: false,
      fontSize: 18,
      fontName: { family: 'Inter', style: 'Italic' },
      letterSpacing: { unit: 'PIXELS', value: 0 },
      lineHeight: { unit: 'PIXELS', value: 28 },
    },
    {
      type: 'TEXT',
      id: 'bold-italic-style',
      name: 'Body/Large/Bold-Italic',
      key: 'bold-italic-style',
      remote: false,
      fontSize: 18,
      fontName: { family: 'Inter', style: 'Bold Italic' },
      letterSpacing: { unit: 'PIXELS', value: 0 },
      lineHeight: { unit: 'PIXELS', value: 28 },
    },
    {
      type: 'TEXT',
      id: 'link-style',
      name: 'Body/Large/Link Bold',
      key: 'link-style',
      remote: false,
      fontSize: 18,
      fontName: { family: 'Inter', style: 'Bold' },
      fontWeight: 700,
      letterSpacing: { unit: 'PIXELS', value: 0 },
      lineHeight: { unit: 'PIXELS', value: 28 },
    },
    {
      type: 'EFFECT',
      id: 'shadow-style',
      name: 'Shadow/shadow-100',
      key: 'shadow-style',
      remote: false,
      effects: [{ type: 'DROP_SHADOW', visible: true, radius: 8, spread: 0, offset: { x: 0, y: 2 }, color: black }],
    },
    {
      type: 'PAINT',
      id: 'gradient-style',
      name: 'Gradient/primary',
      key: 'gradient-style',
      remote: false,
      paints: [
        {
          type: 'GRADIENT_LINEAR',
          visible: true,
          gradientHandlePositions: [
            { x: 0.5, y: 0 },
            { x: 0.5, y: 1 },
            { x: 1, y: 0 },
          ],
          gradientStops: [
            { position: 0, color: white },
            { position: 1, color: { r: 0.8, g: 0.7, b: 1, a: 1 } },
          ],
        },
      ],
    },
    {
      type: 'PAINT',
      id: 'solid-style',
      name: 'Unused/solid',
      key: 'solid-style',
      remote: false,
      paints: [{ type: 'SOLID', visible: true, color: white }],
    },
  ],
  dependencies: [
    {
      id: 'remote-color',
      name: 'Primitive/shadow',
      key: 'remote-color',
      collectionId: 'library',
      resolvedType: 'COLOR',
      valuesByMode: { default: black },
      scopes: ['ALL_FILLS'],
      remote: true,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
  ],
  diagnostics: [],
});

export const createCaptureApi = (snapshot = createSnapshot()) => {
  const variables = [...snapshot.variables, ...snapshot.dependencies];

  return {
    fileKey: snapshot.file.key,
    fileName: snapshot.file.name,
    now: () => snapshot.capturedAt,
    getLocalVariableCollectionsAsync: async () => snapshot.collections,
    getLocalVariablesAsync: async () => snapshot.variables,
    getLocalTextStylesAsync: async () => snapshot.styles.filter((style) => style.type === 'TEXT'),
    getLocalPaintStylesAsync: async () => snapshot.styles.filter((style) => style.type === 'PAINT'),
    getLocalEffectStylesAsync: async () => snapshot.styles.filter((style) => style.type === 'EFFECT'),
    getVariableByIdAsync: async (id) => variables.find((variable) => variable.id === id) ?? null,
  };
};
