import assert from 'node:assert/strict';
import { access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import {
  compareGeneratedWithCommitted,
  generateOutputFiles,
  generateTokenFiles,
  loadConfig,
  normalizeSnapshot,
  outputFileRelativePath,
} from '../src/index.ts';
import { createSnapshot, fontStacks } from './fixtures.mjs';

const SPIRIT_CONFIG_PATH = fileURLToPath(
  new URL('../../../packages/design-tokens/figma-tokens.config.json', import.meta.url),
);

test('generateOutputFiles emits the expected tree with Figma provenance', async () => {
  const document = normalizeSnapshot(createSnapshot(), fontStacks);
  const files = generateOutputFiles(document);
  const byPath = Object.fromEntries(files.map((file) => [outputFileRelativePath(file), file.content]));

  assert.ok(byPath['scss/@tokens.scss'].includes("@forward 'devices';"));
  assert.ok(byPath['scss/global-tokens/_radii.scss'].includes('$radius-100:'));
  assert.ok(byPath['scss/global-tokens/_radii.scss'].includes('full: $radius-full'));
  assert.ok(byPath['scss/global-tokens/_spacing.scss'].includes('$space-700:'));
  assert.ok(byPath['scss/global-tokens/_borders.scss'].includes('1px'));
  assert.ok(byPath['scss/global-tokens/_other.scss'].includes('$css-variable-prefix: spirit-'));
  assert.ok(byPath['scss/global-tokens/_other.scss'].includes('$grid-columns: 12'));
  assert.ok(byPath['scss/global-tokens/_shadows.scss'].includes('var(--spirit-color-'));
  assert.ok(byPath['scss/global-tokens/_gradients.scss'].includes('var(--gradient-angle'));
  assert.ok(byPath['scss/global-tokens/_typography.scss'].includes("$body-large-bold:"));
  assert.equal(byPath['scss/global-tokens/_typography.scss'].includes('italic'), false);
  assert.equal(byPath['scss/global-tokens/_typography.scss'].includes('Link'), false);
  assert.ok(byPath['js/global-tokens/other.ts'].includes('export const gridColumns = 12;'));
  assert.equal(byPath['scss/devices/_devices.scss'].includes('font-family'), false);
  assert.ok(byPath['scss/themes/theme-light-default/_colors.scss'].includes('@mixin color-css-variables'));
  assert.ok(byPath['scss/themes/theme-light-on-brand/_colors.scss'].includes('#fff'));
  assert.ok(byPath['scss/devices/_devices.scss'].includes('$breakpoint-mobile: 0'));
  assert.ok(byPath['scss/devices/_devices.scss'].includes('$font-size-base-mobile: 16px'));
  assert.ok(byPath['js/global-tokens/radii.ts'].includes('export const radius100'));
  assert.ok(byPath['scss/global-tokens/_radii.scss'].startsWith('/* This file was generated by Figma'));
  assert.equal(byPath['scss/global-tokens/index.scss'].startsWith('/* This file was generated by Figma'), false);
});

test('typography expands bound Device font-size and line-height', () => {
  const snapshot = createSnapshot();
  snapshot.collections.find((collection) => collection.id === 'device').variableIds.push('heading-size', 'heading-lh');
  snapshot.variables.push(
    {
      id: 'heading-size',
      name: 'typography/heading/large/font-size',
      key: 'heading-size',
      collectionId: 'device',
      resolvedType: 'FLOAT',
      valuesByMode: { 'device-mobile': 32, 'device-tablet': 40, 'device-desktop': 40 },
      scopes: ['FONT_SIZE'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
    {
      id: 'heading-lh',
      name: 'typography/heading/large/line-height',
      key: 'heading-lh',
      collectionId: 'device',
      resolvedType: 'FLOAT',
      valuesByMode: { 'device-mobile': 38, 'device-tablet': 48, 'device-desktop': 48 },
      scopes: ['LINE_HEIGHT'],
      remote: false,
      hiddenFromPublishing: false,
      codeSyntax: {},
      description: '',
    },
  );
  snapshot.styles.push({
    type: 'TEXT',
    id: 'heading-bold',
    name: 'Heading/Large/Bold',
    key: 'heading-bold',
    remote: false,
    fontSize: 40,
    fontName: { family: 'Inter', style: 'Bold' },
    fontWeight: 700,
    letterSpacing: { unit: 'PIXELS', value: 0 },
    lineHeight: { unit: 'PIXELS', value: 48 },
    boundVariables: {
      fontSize: { type: 'VARIABLE_ALIAS', id: 'heading-size' },
      lineHeight: { type: 'VARIABLE_ALIAS', id: 'heading-lh' },
    },
  });

  const document = normalizeSnapshot(snapshot, fontStacks);
  const files = generateOutputFiles(document);
  const typography = files.find((file) => outputFileRelativePath(file) === 'scss/global-tokens/_typography.scss').content;

  assert.ok(typography.includes('$heading-large-bold:'));
  assert.match(typography, /mobile:[\s\S]*font-size: 2rem/);
  assert.match(typography, /tablet:[\s\S]*font-size: 2\.5rem/);
  assert.match(typography, /desktop:[\s\S]*font-size: 2\.5rem/);
});

test('generateTokenFiles rejects a snapshot from a different Figma file', async () => {
  await assert.rejects(
    generateTokenFiles(
      {
        fileKey: 'other-file',
        brand: 'Spirit',
        out: '/tmp',
        snapshot: '/tmp/missing.json',
        fontStacks,
      },
      createSnapshot(),
    ),
    /does not match config fileKey/,
  );
});

test('Spirit Config snapshot matches committed design-tokens except provenance', async (t) => {
  let config;

  try {
    config = await loadConfig(SPIRIT_CONFIG_PATH);
    await access(config.snapshot);
  } catch {
    t.skip('Spirit plugin snapshot is not present');
    return;
  }

  assert.deepEqual(await compareGeneratedWithCommitted(config), []);
});
