import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { compareGeneratedWithCommitted, contentsMatchIgnoringProvenance, syncTokens } from '../src/index.ts';
import { createSnapshot, fontStacks } from './fixtures.mjs';

const configFor = (out, snapshotPath) => ({
  fileKey: 'BXRF3VABXQm2TGkL0nwS4i',
  brand: 'Spirit',
  out,
  snapshot: snapshotPath,
  fontStacks,
});

test('syncTokens writes, updates, and deletes generated files', async () => {
  const temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), 'figma-tokens-sync-'));
  const snapshotPath = path.join(temporaryDirectory, 'snapshot.json');
  const out = path.join(temporaryDirectory, 'src');

  try {
    await writeFile(snapshotPath, JSON.stringify(createSnapshot()));
    await mkdir(path.join(out, 'scss'), { recursive: true });
    await writeFile(path.join(out, 'scss', 'stale.scss'), 'gone\n');
    await writeFile(path.join(out, 'README.md'), 'keep me\n');

    const first = await syncTokens({ config: configFor(out, snapshotPath) });
    const radii = await readFile(path.join(out, 'scss/global-tokens/_radii.scss'), 'utf8');

    assert.ok(first.changes.some((change) => change.type === 'added'));
    assert.ok(first.changes.some((change) => change.file.endsWith('stale.scss') && change.type === 'deleted'));
    assert.ok(radii.startsWith('/* This file was generated by Figma'));
    assert.deepEqual((await readdir(out)).sort(), ['README.md', 'js', 'scss']);
    assert.equal(await readFile(path.join(out, 'README.md'), 'utf8'), 'keep me\n');

    const second = await syncTokens({ config: configFor(out, snapshotPath) });
    assert.deepEqual(second.changes, []);

    const dryRun = await syncTokens({ config: configFor(out, snapshotPath), dryRun: true });
    assert.deepEqual(dryRun.changes, []);
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
});

test('syncTokens check mode reports drift without writing', async () => {
  const temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), 'figma-tokens-check-'));
  const snapshotPath = path.join(temporaryDirectory, 'snapshot.json');
  const out = path.join(temporaryDirectory, 'src');

  try {
    await writeFile(snapshotPath, JSON.stringify(createSnapshot()));
    await assert.rejects(syncTokens({ config: configFor(out, snapshotPath), check: true }), /out of date/);
    await assert.rejects(readdir(path.join(out, 'scss')));
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
});

test('parity comparison ignores provenance comments', async () => {
  const generated = "/* This file was generated by Figma, don't change manually */\n$radius-100: 0.125rem !default;\n";
  const committed = "/* This file was generated by Supernova, don't change manually */\n$radius-100: 0.125rem !default;\n";

  assert.equal(contentsMatchIgnoringProvenance(generated, committed), true);

  const temporaryDirectory = await mkdtemp(path.join(os.tmpdir(), 'figma-tokens-parity-'));
  const snapshotPath = path.join(temporaryDirectory, 'snapshot.json');
  const out = path.join(temporaryDirectory, 'src');

  try {
    await writeFile(snapshotPath, JSON.stringify(createSnapshot()));
    await syncTokens({ config: configFor(out, snapshotPath) });
    assert.deepEqual(await compareGeneratedWithCommitted(configFor(out, snapshotPath)), []);
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
});
