/* This file was generated by Supernova, don't change manually */
export const accent01BackgroundBasic = '#b60000';
export const accent01BackgroundSubtle = '#b60000';
export const accent01BorderBasic = '#b60000';
export const accent01BorderSubtle = '#1a1b1b00';
export const accent01ContentBasic = '#fff';
export const accent01ContentSubtle = '#fce5e5';
export const accent01StateActive = '#facccc';
export const accent01StateDefault = '#fef2f2';
export const accent01StateHover = '#fce5e5';

export const accent02BackgroundBasic = '#ffbe00';
export const accent02BackgroundSubtle = '#fff7ee';
export const accent02BorderBasic = '#ffcb3b';
export const accent02BorderSubtle = '#fff8e5';
export const accent02ContentBasic = '#ff6a00';
export const accent02ContentSubtle = '#fff8e5';
export const accent02StateActive = '#cc9800';
export const accent02StateDefault = '#ffbe00';
export const accent02StateHover = '#e5ab00';

export const accent03BackgroundBasic = '#404040';
export const accent03BackgroundSubtle = '#f2f2f2';
export const accent03BorderBasic = '#404040';
export const accent03BorderSubtle = '#f2f2f2';
export const accent03ContentBasic = '#404040';
export const accent03ContentSubtle = '#f2f2f2';
export const accent03StateActive = '#d9d9d9';
export const accent03StateDefault = '#f2f2f2';
export const accent03StateHover = '#e5e5e5';

export const accent04BackgroundBasic = '#006e36';
export const accent04BackgroundSubtle = '#f2f9f5';
export const accent04BorderBasic = '#006e36';
export const accent04BorderSubtle = '#f2f9f5';
export const accent04ContentBasic = '#006e36';
export const accent04ContentSubtle = '#f2f9f5';
export const accent04StateActive = '#cce8d9';
export const accent04StateDefault = '#f2f9f5';
export const accent04StateHover = '#e5f3ec';

export const accent05BackgroundBasic = '#e61f60';
export const accent05BackgroundSubtle = '#f5f6fa';
export const accent05BorderBasic = '#e61f60';
export const accent05BorderSubtle = '#f28faf';
export const accent05ContentBasic = '#e61f60';
export const accent05ContentSubtle = '#fff';
export const accent05StateActive = '#cf1652';
export const accent05StateDefault = '#e61f60';
export const accent05StateHover = '#d91958';

export const accent06BackgroundBasic = '#ffcb3b';
export const accent06BackgroundSubtle = '#fffaeb';
export const accent06BorderBasic = '#ffd562';
export const accent06BorderSubtle = '#ffefc4';
export const accent06ContentBasic = '#cca22f';
export const accent06ContentSubtle = '#ffcb3b';
export const accent06StateActive = '#ffda75';
export const accent06StateDefault = '#ffcb3b';
export const accent06StateHover = '#ffd562';

export const backgroundBackdrop = '#1a1b1b80';

export const backgroundInteractiveStateActive = '#1a1b1b40';
export const backgroundInteractiveStateDefault = '#fff0';
export const backgroundInteractiveStateHover = '#1a1b1b26';

export const backgroundPrimary = '#940000';
export const backgroundSecondary = '#f9f9f9';
export const backgroundTertiary = '#fbf7f4';

export const borderBasic = '#ffffff80';
export const borderFocus = '#ffbe00';

export const borderInteractiveStateActive = '#a5a5a5';
export const borderInteractiveStateDefault = '#bfbfbf';
export const borderInteractiveStateHover = '#b2b2b2';
export const borderInteractiveStateSelected = '#ffbe00';

export const componentButtonPlainBorder = '#fff0';
export const componentButtonPlainContent = '#fff';
export const componentButtonPlainStateActive = '#ffffff26';
export const componentButtonPlainStateDefault = '#fff0';
export const componentButtonPlainStateHover = '#ffffff1a';

export const componentButtonPrimaryBorder = '#ffbe00';
export const componentButtonPrimaryContent = '#000';
export const componentButtonPrimaryStateActive = '#ffd24d';
export const componentButtonPrimaryStateDefault = '#ffbe00';
export const componentButtonPrimaryStateHover = '#ffcb33';

export const componentButtonSecondaryBorder = '#fff';
export const componentButtonSecondaryContent = '#fff';
export const componentButtonSecondaryStateActive = '#ffffff26';
export const componentButtonSecondaryStateDefault = '#fff0';
export const componentButtonSecondaryStateHover = '#ffffff1a';

export const componentButtonTertiaryBorder = '#1a1b1b00';
export const componentButtonTertiaryContent = '#fff';
export const componentButtonTertiaryStateActive = '#1a1b1b4d';
export const componentButtonTertiaryStateDefault = '#1a1b1b33';
export const componentButtonTertiaryStateHover = '#1a1b1b40';

export const componentHeaderBackground = '#1a1b1b00';
export const componentHeaderBorder = '#ffffff80';

export const componentNavigationItemBackgroundStateActive = '#1a1b1b33';
export const componentNavigationItemBackgroundStateDefault = '#fff0';
export const componentNavigationItemBackgroundStateHover = '#1a1b1b26';
export const componentNavigationItemBackgroundStateSelected = '#b60000';
export const componentNavigationItemStateActive = '#e5e5e5';
export const componentNavigationItemStateDefault = '#fff';
export const componentNavigationItemStateHover = '#fff';
export const componentNavigationItemStateSelected = '#fff';
export const componentNavigationItemStripeStateSelected = '#ffbe00';
export const componentNavigationItemStripeStateUnselected = '#ffffff40';

export const componentPaginationSelectedBorder = '#e5ab00';
export const componentPaginationSelectedContent = '#000';
export const componentPaginationSelectedStateActive = '#ffd24d';
export const componentPaginationSelectedStateDefault = '#ffbe00';
export const componentPaginationSelectedStateHover = '#ffcb33';
export const componentPaginationUnselectedBorder = '#fff';
export const componentPaginationUnselectedContent = '#fff';
export const componentPaginationUnselectedStateActive = '#ef6666';
export const componentPaginationUnselectedStateDefault = '#e93333';
export const componentPaginationUnselectedStateHover = '#ec4d4d';

export const componentPricingPlanHighlightedBackground = '#fff7ee';
export const componentPricingPlanHighlightedBorder = '#ffcb3b';
export const componentPricingPlanHighlightedContent = '#ff6a00';

export const componentTagSelectedBackground = '#ffbe00';
export const componentTagSelectedBorder = '#fbbb00';
export const componentTagSelectedContent = '#202020';

export const componentToggleSelectedBorder = '#a07eff';
export const componentToggleSelectedContent = '#fff';
export const componentToggleSelectedStateActive = '#3e9b4f';
export const componentToggleSelectedStateDefault = '#327c3f';
export const componentToggleSelectedStateHover = '#388b47';
export const componentToggleUnselectedBorder = '#a07eff';
export const componentToggleUnselectedContent = '#4e2ea6';
export const componentToggleUnselectedStateActive = '#e4daff';
export const componentToggleUnselectedStateDefault = '#fff';
export const componentToggleUnselectedStateHover = '#f1edff';

export const disabledBackground = '#ffffff4d';
export const disabledBorder = '#fff3';
export const disabledContent = '#f2f2f2';
export const disabledForeground = '#fff3';

export const emotionDangerBackgroundBasic = '#e40000';
export const emotionDangerBackgroundSubtle = '#fce5e5';
export const emotionDangerBorderBasic = '#e93333';
export const emotionDangerBorderSubtle = '#ef6666';
export const emotionDangerContentBasic = '#720000';
export const emotionDangerContentSubtle = '#fff';
export const emotionDangerStateActive = '#ec4d4d';
export const emotionDangerStateDefault = '#e40000';
export const emotionDangerStateHover = '#e93333';

export const emotionInformativeBackgroundBasic = '#0066d8';
export const emotionInformativeBackgroundSubtle = '#e5f0fb';
export const emotionInformativeBorderBasic = '#3385e0';
export const emotionInformativeBorderSubtle = '#66a3e8';
export const emotionInformativeContentBasic = '#00336c';
export const emotionInformativeContentSubtle = '#fff';
export const emotionInformativeStateActive = '#4d94e4';
export const emotionInformativeStateDefault = '#0066d8';
export const emotionInformativeStateHover = '#3385e0';

export const emotionSuccessBackgroundBasic = '#3e9b4f';
export const emotionSuccessBackgroundSubtle = '#ecf5ed';
export const emotionSuccessBorderBasic = '#65af72';
export const emotionSuccessBorderSubtle = '#8bc395';
export const emotionSuccessContentBasic = '#1f4e28';
export const emotionSuccessContentSubtle = '#fff';
export const emotionSuccessStateActive = '#78b984';
export const emotionSuccessStateDefault = '#3e9b4f';
export const emotionSuccessStateHover = '#65af72';

export const emotionWarningBackgroundBasic = '#f27d00';
export const emotionWarningBackgroundSubtle = '#fef2e5';
export const emotionWarningBorderBasic = '#f59733';
export const emotionWarningBorderSubtle = '#f7b166';
export const emotionWarningContentBasic = '#793f00';
export const emotionWarningContentSubtle = '#fff';
export const emotionWarningStateActive = '#f6a44d';
export const emotionWarningStateDefault = '#f27d00';
export const emotionWarningStateHover = '#f59733';

export const focusFocusRingColor01 = '#d2c2ffb2';

export const formFieldDanger = '#fce5e5';

export const formFieldFillBackgroundStateActive = '#fff';
export const formFieldFillBackgroundStateDefault = '#fff';
export const formFieldFillBackgroundStateHover = '#f9f9f9';
export const formFieldFillBorderStateActive = '#fff0';
export const formFieldFillBorderStateDefault = '#fff0';
export const formFieldFillBorderStateHover = '#fff0';
export const formFieldFillBorderStateSelected = '#ffbe00';
export const formFieldFillContent = '#202020';
export const formFieldFillPlaceholder = '#666';

export const formFieldHelperText = '#d9d9d9';
export const formFieldLabel = '#fff';

export const formFieldOutlineBackgroundStateActive = '#fff';
export const formFieldOutlineBackgroundStateDefault = '#1a1b1b00';
export const formFieldOutlineBackgroundStateHover = '#fff';
export const formFieldOutlineBorderStateActive = '#fff';
export const formFieldOutlineBorderStateDefault = '#fff';
export const formFieldOutlineBorderStateHover = '#fff';
export const formFieldOutlineBorderStateSelected = '#fff';
export const formFieldOutlineContent = '#fff';
export const formFieldOutlinePlaceholder = '#fff';

export const formFieldSuccess = '#78b984';
export const formFieldWarning = '#f6a44d';

export const gradientBasicOverlayColor01 = '#606060';
export const gradientBasicOverlayColor02 = '#60606000';

export const gradientPrimaryColor01 = '#c30c13';
export const gradientPrimaryColor02 = '#e4192a';
export const gradientPrimaryColor03 = '#e4192a';

export const gradientSecondaryColor01 = '#c30c13';
export const gradientSecondaryColor02 = '#e4192a';
export const gradientSecondaryColor03 = '#e4192a';

export const gradientSkeletonColor01 = '#e5e5e5';
export const gradientSkeletonColor02 = '#fff';
export const gradientSkeletonColor03 = '#e5e5e5';

export const linkPrimaryStateActive = '#e5e5e5';
export const linkPrimaryStateDefault = '#fff';
export const linkPrimaryStateHover = '#f2f2f2';

export const linkSecondaryStateActive = '#f9f9f9';
export const linkSecondaryStateDefault = '#e5e5e5';
export const linkSecondaryStateHover = '#f2f2f2';

export const linkStateVisited = '#ffbe00';

export const linkTertiaryStateActive = '#f9f9f9';
export const linkTertiaryStateDefault = '#ccc';
export const linkTertiaryStateHover = '#f2f2f2';

export const neutralBackgroundBasic = '#202020';
export const neutralBackgroundSubtle = '#f2f2f2';
export const neutralBorderBasic = '#202020';
export const neutralBorderSubtle = '#bfbfbf';
export const neutralContentBasic = '#202020';
export const neutralContentSubtle = '#fff';
export const neutralStateActive = '#535353';
export const neutralStateDefault = '#202020';
export const neutralStateHover = '#404040';

export const selectedBackgroundBasic = '#ffcb3b';
export const selectedBackgroundSubtle = '#fff3';
export const selectedBorderBasic = '#a68426';
export const selectedBorderSubtle = '#ffcf43';
export const selectedContentBasic = '#202020';
export const selectedContentSubtle = '#404040';
export const selectedStateActive = '#ffd24d';
export const selectedStateDefault = '#ffbe00';
export const selectedStateHover = '#ffcb33';

export const shadowShadow100Color01 = '#00000026';

export const shadowShadow200Color01 = '#0003';

export const shadowShadow300Color01 = '#00000040';

export const shadowShadow400Color01 = '#00000040';

export const textPrimary = '#f9f9f9';
export const textSecondary = '#d9d9d9';
export const textTertiary = '#b2b2b2';
