name: 🧩 Component Analysis

on:
  schedule:
    - cron: '0 6 * * 1' # every Monday at 6:00

jobs:
  omlet_analyze:
    name: 🍳 Analyzing Components
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          # Omlet.dev uses Git History for analysis; Disable shallow clone
          fetch-depth: 0

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-install

      - name: Analyze
        run: npx omlet analyze
        env:
          OMLET_TOKEN: ${{ secrets.OMLET_TOKEN }}
