name: 🧩 Component Analysis

on:
  schedule:
    - cron: '0 6 * * 1' # every Monday at 6:00

jobs:
  omlet_analyze:
    name: 🍳 Analyzing Components
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          # Omlet.dev uses Git History for analysis; Disable shallow clone
          fetch-depth: 0

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-install

      - name: Analyze
        run: npx omlet analyze
        env:
          OMLET_TOKEN: ${{ secrets.OMLET_TOKEN }}
