name: 🔍 Git Checks

on:
  workflow_call:

jobs:
  block-fixup-merge:
    name: 🚫 Merge Blocked by Git Fixup
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # v2.0.0

  commitlint:
    name: 🧾 Commit Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-install

      - name: Commits Check
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
