name: Pull Request Meta

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  process_pr_meta:
    name: Process PR meta
    runs-on: ubuntu-24.04
    steps:
      - name: Assign to author
        uses: toshimaru/auto-author-assign@3e19bfc990cb1cf0589dce95e9f75289bb1e22de # v3.0.3

      - name: Add labels
        uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5.0.0
        with:
          configuration-path: .github/pr-labeler.yaml
        env:
          GITHUB_TOKEN: ${{ github.token}}
