name: 💥 Supernova

concurrency:
  group: supernova-io
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  has-tags:
    name: 🏷️ Analyze Tags
    runs-on: ubuntu-24.04

    outputs:
      has-tag: ${{ steps.check-tag-exists.outputs.has-tag }}

    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          # Even though this is set, shallow clones do not always retrieve all tags correctly
          fetch-tags: true
          # So we need to fetch full history, including all tags
          fetch-depth: 0

      - name: Check Tag On Commit
        id: check-tag-exists
        uses: ./.github/actions/has-tags

  publish:
    name: 🚀 Publish Supernova Documentation
    needs: has-tags
    if: ${{ needs.has-tags.outputs.has-tag == 'true' }}
    runs-on: ubuntu-24.04
    environment: supernova-io
    permissions:
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install system dependencies (libsecret)
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-1-0 dbus

      - name: Set up Node.js
        uses: ./.github/actions/setup-node

      - name: Publish Supernova Documentation
        run: npx @supernovaio/cli publish-documentation --apiKey="${{secrets.SUPERNOVA_TOKEN}}" --designSystemId="${{secrets.SUPERNOVA_DS_ID}}"
