name: 🔍 Code Quality Checks

on:
  # Run this workflow on push to branches only (not tags)
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 9 * * *' # every day at 9:00

permissions:
  actions: write
  contents: read

env:
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_VERBOSE_LOGGING: true
  NX_NO_CLOUD: true
  CACHE_KEY: repository-cache-key-${{ github.run_id }}

jobs:
  install-build:
    name: 🧶 Install Deps and 🏗️ Build Design Tokens
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      HUSKY: 0

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-install

      - name: Build
        run: yarn workspace @alma-oss/spirit-design-tokens build

      - name: Save Repository to Cache
        id: save-repository-cache
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: ./
          key: ${{ env.CACHE_KEY }}

  lint:
    name: 📐 Code Linting
    needs: [install-build]
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      HUSKY: 0

    steps:
      - name: Restore Repository from Cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        id: restore-repository-cache
        with:
          path: ./
          key: ${{ env.CACHE_KEY }}

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Lint
        run: yarn lint

  unit-tests:
    name: 🧪 Unit Testing
    needs: [install-build]
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      HUSKY: 0

    steps:
      - name: Restore Repository from Cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        id: restore-repository-cache
        with:
          path: ./
          key: ${{ env.CACHE_KEY }}

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Unit Tests
        run: yarn test:unit:coverage

      - name: Upload Coverage Artifacts
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: coverage-reports
          path: |
            packages/web/.coverage/lcov.info
            packages/web-react/.coverage/lcov.info
            packages/analytics/.coverage/lcov.info
            packages/common/.coverage/lcov.info
            packages/codemods/.coverage/lcov.info
          if-no-files-found: ignore
          retention-days: 1

  format:
    name: 💅 Code Formatting
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      HUSKY: 0

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-install

      - name: Check Code-Style Format
        run: yarn format:check

  types:
    name: 📘 Type Checking
    needs: [install-build]
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      HUSKY: 0

    steps:
      - name: Restore Repository from Cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        id: restore-repository-cache
        with:
          path: ./
          key: ${{ env.CACHE_KEY }}

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Types Check
        run: yarn types

  publish-coverage:
    name: 📊 Publish Code Coverage
    needs: [unit-tests]
    if: always()
    uses: ./.github/workflows/publish-coverage.yaml

  cleanup:
    name: 🧹 Cleanup
    needs: [lint, unit-tests, types, publish-coverage]
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    # Ensure this job runs regardless of previous job outcomes
    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # @see: https://github.com/actions/cache/blob/main/tips-and-workarounds.md#force-deletion-of-caches-overriding-default-cache-eviction-policy
      - name: Cleanup cache
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "${{ env.CACHE_KEY }}" --confirm
        env:
          GH_TOKEN: ${{ github.token}}
