name: 🧪 Tests

on:
  workflow_call:

permissions:
  contents: read

env:
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_VERBOSE_LOGGING: true
  NX_NO_CLOUD: true

jobs:
  unit-tests:
    name: 🧪 Unit Testing
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      HUSKY: 0

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-install

      - name: Build
        run: yarn workspace @alma-oss/spirit-design-tokens build

      - name: Unit Tests
        run: yarn test:unit:coverage

      - name: Upload Coverage Artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: coverage-reports
          path: |
            packages/web/.coverage/lcov.info
            packages/web-react/.coverage/lcov.info
            packages/analytics/.coverage/lcov.info
            packages/common/.coverage/lcov.info
            packages/codemods/.coverage/lcov.info
          if-no-files-found: ignore
          retention-days: 1

  publish-coverage:
    name: 📊 Publish Code Coverage
    needs: [unit-tests]
    if: always()
    uses: ./.github/workflows/publish-coverage.yaml
